export const DAILY_PHRASES: { text: string; author: string }[] = [
  { text: "El despertar no es cambiar quién eres, sino recordar quién eres realmente.", author: "Siddhartha Gautama" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda" },
  { text: "Conócete a ti mismo y conocerás el universo y los dioses.", author: "Sócrates" },
  { text: "La conciencia es el campo donde todo ocurre. Eres ese campo.", author: "Eckhart Tolle" },
  { text: "Cuando te das cuenta de que nada te falta, el mundo entero te pertenece.", author: "Lao Tse" },
  { text: "No eres una gota en el océano. Eres el océano entero en una gota.", author: "Rumi" },
  { text: "El corazón es el faro del alma. Síguelo siempre.", author: "Proverbio sufí" },
  { text: "No se trata de encontrar la salida, sino de ver que nunca estuviste encerrado.", author: "Mooji" },
  { text: "El silencio es el lenguaje que Dios habla, todo lo demás es una mala traducción.", author: "Rumi" },
  { text: "La vida es un misterio que hay que vivir, no un problema que haya que resolver.", author: "Rabindranath Tagore" },
  { text: "El alma no tiene enfermedad, la medicina es el alma.", author: "Platón" },
  { text: "Todo lo que necesitas está al otro lado del miedo.", author: "Jack Canfield" },
  { text: "La mente es como el agua. Cuando está quieta, está clara.", author: "Proverbio zen" },
  { text: "Dentro de ti hay una quietud y un santuario al que puedes retirarte en cualquier momento.", author: "Hermann Hesse" },
  { text: "La meditación no es escapar de la realidad, sino volver a casa.", author: "Proverbio tibetano" },
  { text: "La respiración es el puente entre el cuerpo y la mente.", author: "Thich Nhat Hanh" },
  { text: "El alma que habla con el alma tiene el poder de encontrar el alma de los demás.", author: "Proverbio sufí" },
  { text: "Vivir es la cosa más rara del mundo. La mayoría de la gente existe, eso es todo.", author: "Oscar Wilde" },
  { text: "El universo te dará lo que más temes o lo que más amas. Depende de cuál sea más fuerte.", author: "Proverbio espiritual" },
  { text: "El secreto de la vida es no tener secretos. No tengas nada que esconder.", author: "Eckhart Tolle" },
  { text: "Las palabras son la sombra de los pensamientos.", author: "Proverbio" },
  { text: "No es lo que te pasa, sino cómo lo tomas lo que importa.", author: "Epicteto" },
  { text: "La verdadera espiritualidad está en vivir el momento presente.", author: "Thich Nhat Hanh" },
  { text: "Cuando el discípulo está listo, el maestro aparece.", author: "Proverbio budista" },
  { text: "El silencio del alma produce la paz interior que refleja la verdadera naturaleza del ser.", author: "Anónimo" },
  { text: "Cuando cambias la forma en que miras las cosas, las cosas que miras cambian.", author: "Wayne Dyer" },
  { text: "El que vence a los demás es fuerte, el que se vence a sí mismo es todopoderoso.", author: "Lao Tse" },
  { text: "El alma que nunca ha experimentado un día de lluvia no puede apreciar el arcoíris.", author: "Proverbio" },
  { text: "En el silencio de la noche, el alma se conecta con el universo.", author: "Anónimo" },
  { text: "El yoga no es tocar los pies. Es lo que aprendes en el camino al doblarte.", author: "Jigar Gor" },
  { text: "Las constelaciones revelan las lealtades invisibles que nos mantienen atrapados.", author: "Bert Hellinger" },
  { text: "El tarot no predice el futuro, revela el presente.", author: "Anónimo" },
  { text: "Tu cuerpo habla, escúchalo antes de que tenga que gritar.", author: "Anónimo" },
  { text: "La sanación comienza cuando das permiso para sentir.", author: "Anónimo" },
  { text: "Las emociones son energía en movimiento. Déjalas fluir.", author: "Anónimo" },
  { text: "La meditación no es pensar en nada, es estar en todo.", author: "Thich Nhat Hanh" },
  { text: "Cada exhalación es una oportunidad para soltar lo que ya no sirve.", author: "Anónimo" },
  { text: "El retiro es donde la vida te enseña lo que el ruido te impide escuchar.", author: "Anónimo" },
  { text: "El crecimiento personal no tiene punto final, solo puntos de inflexión.", author: "Anónimo" },
  { text: "El coaching espiritual no te dice qué hacer, te ayuda a escuchar lo que ya sabes.", author: "Anónimo" },
  { text: "Cuando respiras conscientemente, le dices al cuerpo que estás seguro.", author: "Anónimo" },
  { text: "Cada ritual es una puerta entre lo que eres y lo que puedes ser.", author: "Anónimo" },
  // ————— Introspección profunda —————
  { text: "Antes de cambiar el mundo, pregúntate qué parte de ti mismo quieres dejar morir.", author: "Anónimo" },
  { text: "No eres tus pensamientos. Eres el que los observa.", author: "Eckhart Tolle" },
  { text: "La herida que más evitas es la que más necesita ser mirada.", author: "Anónimo" },
  { text: "¿Cuántas máscaras llevas puestas sin darte cuenta?", author: "Carl Jung" },
  { text: "El dolor no es tu enemigo. Es un mensajero que pide tu atención.", author: "Anónimo" },
  { text: "Lo que odias de otros es, casi siempre, lo que no aceptas de ti mismo.", author: "Carl Jung" },
  { text: "No necesitas ser mejor. Necesitas ser más honesto contigo mismo.", author: "Anónimo" },
  { text: "El silencio revela lo que el ruido esconde.", author: "Anónimo" },
  { text: "Cuando dejas de correr, descubres hacia dónde ibas.", author: "Anónimo" },
  { text: "La soledad bien elegida es un camino. La huida es otra cosa.", author: "Anónimo" },
  { text: "Cada respuesta que buscas fuera ya está dentro de ti.", author: "Rumi" },
  { text: "El miedo solo tiene poder cuando le das permiso para dirigir tu vida.", author: "Anónimo" },
  { text: "No hay crecimiento sin incomodidad. No hay transformación sin soltar.", author: "Anónimo" },
  { text: "¿Quién serías sin la historia que te cuentas sobre ti mismo?", author: "Anónimo" },
  { text: "La autenticidad cuesta. La mentira también. Elige cuál pagar.", author: "Anónimo" },
  { text: "El alma no pide perfección, pide presencia.", author: "Anónimo" },
  { text: "Lo que resistes persiste. Lo que aceptas se transforma.", author: "Anónimo" },
  { text: "No estás roto. Estás en proceso.", author: "Anónimo" },
  { text: "El perdón no es para el otro. Es para dejar de cargar tu propia carga.", author: "Anónimo" },
  { text: "Mira hacia dentro. Ahí está el universo que buscas fuera.", author: "Proverbio hindú" },
  { text: "La ansiedad es el cuerpo pidiendo lo que la mente no se atreve a admitir.", author: "Anónimo" },
  { text: "No confundas estar ocupado con estar despierto.", author: "Anónimo" },
  { text: "Cada mañana tienes dos opciones: seguir dormido con tus miedos o despertar con tu verdad.", author: "Anónimo" },
  { text: "El alma crece en la oscuridad, como la raíz bajo la tierra.", author: "Anónimo" },
  { text: "¿Qué estás evitando sentir? Ahí empieza tu sanación.", author: "Anónimo" },
  { text: "La comparación es la muerte de la autenticidad.", author: "Anónimo" },
  { text: "No te preguntes qué quieres de la vida. Pregúntate qué vida quieres sentir.", author: "Anónimo" },
  { text: "El ego grita. El alma susurra. Aprende a distinguirlos.", author: "Anónimo" },
  { text: "La paz no es la ausencia de tormenta, es la calma que construyes dentro.", author: "Anónimo" },
  { text: "Lo que no expresas con palabras, tu cuerpo lo expresa con síntomas.", author: "Anónimo" },
  { text: "El silencio no es vacío. Es donde nace la respuesta.", author: "Anónimo" },
  { text: "¿Cuándo fue la última vez que te hiciste una pregunta difícil?", author: "Anónimo" },
  { text: "La tristeza no es debilidad. Es el alma procesando algo profundo.", author: "Anónimo" },
  { text: "No necesitas permiso para ser quien realmente eres.", author: "Anónimo" },
  { text: "El desapego no es no sentir. Es sentir sin aferrarse.", author: "Anónimo" },
  { text: "La verdad duele menos que una mentira sostenida.", author: "Anónimo" },
  { text: "Mira tu sombra con compasión. Esa parte de ti también merece amor.", author: "Carl Jung" },
  { text: "No hay atajos hacia la paz interior. Hay presencia, y hay huida. Elige cada día.", author: "Anónimo" },
  { text: "El universo no te da lo que pides. Te da lo que necesitas para despertar.", author: "Anónimo" },
  { text: "¿Estás viviendo tu vida o la que otros esperan de ti?", author: "Anónimo" },
  { text: "La intuición es el alma hablando. Aprende a escucharla.", author: "Anónimo" },
  { text: "No eres responsable de curar a nadie, pero sí de sanar tu propia herida.", author: "Anónimo" },
  { text: "El amor propio no es ego. Es la base desde la que amas a los demás.", author: "Anónimo" },
  { text: "Cada cicatriz es una prueba de que sobreviviste algo que intentó romperte.", author: "Anónimo" },
  { text: "La gratitud transforma lo que tienes en suficiente.", author: "Anónimo" },
  { text: "El camino espiritual no es lineal. Hay días de luz y días de oscuridad. Ambos son parte.", author: "Anónimo" },
  { text: "¿Qué parte de ti has estado abandonando para que otros estén cómodos?", author: "Anónimo" },
  { text: "La verdadera libertad es no necesitar aprobación para ser tú mismo.", author: "Anónimo" },
  { text: "El silencio de la mente es el primer paso hacia la claridad.", author: "Anónimo" },
  { text: "No te culpes por lo que no sabías. Sigue adelante con amor.", author: "Anónimo" },
  { text: "El alma no compite. Tiene su propio ritmo.", author: "Anónimo" },
  { text: "La sanación es recordar que siempre estuviste completo.", author: "Anónimo" },
  { text: "¿Qué te da miedo de ti mismo? Ahí está tu crecimiento.", author: "Anónimo" },
  { text: "No busques la respuesta. Aprende a habitar la pregunta.", author: "Anónimo" },
  { text: "El cuerpo es el primer territorio de tu despertar. Escúchalo.", author: "Anónimo" },
  { text: "La empatía real comienza cuando dejas de proyectar y empiezas a ver.", author: "Anónimo" },
  { text: "No eres lo que te pasó. Eres lo que hiciste con eso.", author: "Anónimo" },
  { text: "El perdón verdadero es soltar la esperanza de un pasado diferente.", author: "Anónimo" },
  { text: "La vida no te está castigando. Te está enseñando.", author: "Anónimo" },
  { text: "¿Cuánto tiempo llevas posponiendo lo que tu alma te pide?", author: "Anónimo" },
  { text: "La vulnerabilidad no es debilidad. Es el acto más valiente de conexión.", author: "Brené Brown" },
  { text: "El silencio entre tus pensamientos es donde habita tu esencia.", author: "Anónimo" },
  { text: "No necesitas tenerlo todo resuelto para empezar a vivir.", author: "Anónimo" },
  { text: "La alegría auténtica nace cuando dejas de buscarla y empiezas a habitarla.", author: "Anónimo" },
  { text: "Tu herida más profunda es también tu mayor fuente de sabiduría.", author: "Anónimo" },
  { text: "El amor no es algo que encuentras. Es algo que reconoces.", author: "Anónimo" },
  { text: "¿Qué estás haciendo hoy que tu yo de dentro de 10 años te agradecerá?", author: "Anónimo" },
  { text: "La espiritualidad no es huir del mundo. Es mirarlo con otros ojos.", author: "Anónimo" },
  { text: "El perdón es un viaje, no un destino. Y el destino eres tú mismo.", author: "Anónimo" },
  { text: "No te pierdas cuidando de otros mientras tú te desconectas de ti.", author: "Anónimo" },
  { text: "La paz interior se construye en silencio, no en palabras.", author: "Anónimo" },
  { text: "Cada respiración es una oportunidad para volver a ti mismo.", author: "Anónimo" },
  { text: "El alma no pide tu perfección. Pide tu presencia.", author: "Anónimo" },
  { text: "¿Qué parte de tu vida pides permiso para habitar plenamente?", author: "Anónimo" },
  { text: "La verdadera sanación es recordar que siempre estuviste entero.", author: "Anónimo" },
  { text: "El crecimiento espiritual no es acumular conocimiento. Es soltar identidad.", author: "Anónimo" },
  { text: "No te avergüences de tu oscuridad. Es allí donde crece la luz.", author: "Anónimo" },
  { text: "La vida te habla en símbolos. Aprende a leer los tuyos.", author: "Anónimo" },
  { text: "¿Cuándo fue la última vez que te escuchaste a ti mismo en silencio?", author: "Anónimo" },
  { text: "El perdón es liberarte de la cárcel que construiste con tu propio rencor.", author: "Anónimo" },
  { text: "No eres tus emociones. Eres el que las siente.", author: "Anónimo" },
  { text: "La autenticidad es la forma más radical de amor propio.", author: "Anónimo" },
  { text: "El alma crece en la incomodidad, como la raíz busca la profundidad.", author: "Anónimo" },
  { text: "¿Qué verdad llevas años evitando mirar?", author: "Anónimo" },
  { text: "La sanación no es un destino. Es una práctica diaria de presencia.", author: "Anónimo" },
  { text: "El silencio no es la ausencia de ruido. Es la presencia de ti mismo.", author: "Anónimo" },
  { text: "No necesitas tener todo claro para dar el siguiente paso.", author: "Anónimo" },
  { text: "El amor propio es la raíz de toda sanación.", author: "Anónimo" },
  { text: "¿Qué parte de ti has estado silenciando para encajar?", author: "Anónimo" },
  { text: "La vida no te debe nada. Pero tú te debes a ti mismo tu verdad.", author: "Anónimo" },
  { text: "El camino espiritual es recordar que nunca estuviste separado.", author: "Anónimo" },
  { text: "No confundas estar en paz con estar anestesiado.", author: "Anónimo" },
  { text: "Cada herida que sanas libera a alguien más que carga la misma.", author: "Anónimo" },
]
