export const DAILY_PHRASES: { text: string; author: string }[] = [
  { text: "El despertar no es cambiar quién eres, sino recordar quién eres realmente.", author: "Siddhartha Gautama" },
  { text: "La paz viene de dentro. No la busques fuera.", author: "Buda" },
  { text: "El universo no es más que un gran eco. Todo lo que das, vuelve.", author: "Proverbio espiritual" },
  { text: "No hay camino hacia la paz, la paz es el camino.", author: "Mahatma Gandhi" },
  { text: "Conócete a ti mismo y conocerás el universo y los dioses.", author: "Sócrates" },
  { text: "Lo único que te impide obtener lo que deseas es la historia que te cuentas a ti mismo.", author: "Don Miguel Ruiz" },
  { text: "La conciencia es el campo donde todo ocurre. Eres ese campo.", author: "Eckhart Tolle" },
  { text: "Cuando te das cuenta de que nada te falta, el mundo entero te pertenece.", author: "Lao Tse" },
  { text: "No eres una gota en el océano. Eres el océano entero en una gota.", author: "Rumi" },
  { text: "La danza entre la oscuridad y la luz es lo que te hace despertar.", author: "Deepak Chopra" },
  { text: "El corazón es el faro del alma. Síguelo siempre.", author: "Proverbio sufí" },
  { text: "Tu vibración atrae tu realidad. Elévate.", author: "Anónimo" },
  { text: "No se trata de encontrar la salida, sino de ver que nunca estuviste encerrado.", author: "Mooji" },
  { text: "Cada persona que cruza tu camino tiene una lección que enseñarte.", author: "Osho" },
  { text: "El silencio es el lenguaje que Dios habla, todo lo demás es una mala traducción.", author: "Rumi" },
  { text: "No puedes cruzar el mar simplemente mirando el agua.", author: "Rabindranath Tagore" },
  { text: "La vida es un misterio que hay que vivir, no un problema que haya que resolver.", author: "Gurú Rabindranath" },
  { text: "El alma no tiene curación, la medicina es el alma.", author: "Platón" },
  { text: "Cada mañana nacemos de nuevo. Lo que hacemos hoy es lo que importa.", author: "Buda" },
  { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama" },
  { text: "Todo lo que necesitas está al otro lado del miedo.", author: "Jack Canfield" },
  { text: "No busques que los acontecimientos sucedan como quieres, sino desear que sucedan como suceden.", author: "Epicteto" },
  { text: "La mente es como el agua. Cuando está quieta, está clara.", author: "Proverbio zen" },
  { text: "Nada es permanente. Todo cambia. Fluir con ello.", author: "Buda" },
  { text: "Sé la luz que ilumina el camino de otros sin buscar la oscuridad para comparar.", author: "Anónimo" },
  { text: "El reino de Dios está dentro de ti. No lo busques en los templos.", author: "Lao Tse" },
  { text: "Lo que piensas, eso te conviertes. Lo que imaginas, eso creas.", author: "Buda" },
  { text: "No hay nada más poderoso que una idea cuyo tiempo ha llegado.", author: "Víctor Hugo" },
  { text: "Tu cuerpo es el templo de tu alma. Cuídalo.", author: "Proverbio hindú" },
  { text: "La gratitud abre la puerta al poder, la sabiduría y la creatividad del universo.", author: "Deepak Chopra" },
  { text: "Cuando la luna no te satisface, mira las estrellas.", author: "Proverbio sufi" },
  { text: "El que tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche" },
  { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
  { text: "Cambia tus pensamientos y cambiarás tu mundo.", author: "Norman Vincent Peale" },
  { text: "La vida es un 10% lo que te ocurre y un 90% cómo reaccionas.", author: "Charles R. Swindoll" },
  { text: "Dentro de ti hay una quietud y un santuario al que puedes retirarte en cualquier momento.", author: "Hermann Hesse" },
  { text: "No te conviertas en lo que eres, sino en lo que siempre has sido.", author: "Friedrich Hölderlin" },
  { text: "Cuando te sientas a oscuras, recuerda que la oscuridad no tiene la culpa de que no veas las estrellas.", author: "Anónimo" },
  { text: "La meditación no es escapar de la realidad, sino volver a casa.", author: "Proverbio tibetano" },
  { text: "No hay atajos para cualquier lugar al que vale la pena llegar.", author: "Proverbio" },
  { text: "La respiración es el puente entre el cuerpo y la mente.", author: "Thich Nhat Hanh" },
  { text: "El mayor descubrimiento de mi generación es que un ser humano puede alterar su vida cambiando sus actitudes mentales.", author: "William James" },
  { text: "No te preocupes por los problemas, preocupate por las soluciones.", author: "Anónimo" },
  { text: "Lo que das a los demás, te lo das a ti mismo.", author: "Proverbio" },
  { text: "La intención es el punto de partida de todo logro.", author: "W. Clement Stone" },
  { text: "No busques ser exitoso, busca ser valioso.", author: "Albert Einstein" },
  { text: "El amor es la fuerza más humilde, pero la más poderosa de que dispone el mundo.", author: "Mahatma Gandhi" },
  { text: "Los ángeles pueden volar porque se toman la vida a la ligera.", author: "Antoine de Saint-Exupéry" },
  { text: "La vida es breve para los que lamentan, larga para los que aman, eterna para los que sueñan.", author: "Proverbio" },
  { text: "No mires al reloj, haz lo que él hace: sigue adelante.", author: "Joel Osteen" },
  { text: "Los obstáculos son esas cosas espantosas que ves cuando apartas los ojos de tu meta.", author: "Henry Ford" },
  { text: "La alegría no es ausencia de problemas, sino capacidad de enfrentarlos.", author: "Mahatma Gandhi" },
  { text: "Si siempre haces lo que siempre has hecho, siempre obtendrás lo que siempre has obtenido.", author: "Tony Robbins" },
  { text: "La prudencia de los pequeños es la desconfianza; la de los grandes, la confianza.", author: "Oscar Wilde" },
  { text: "El alma que habla con el alma tiene el poder de encontrar el alma de los demás.", author: "Proverbio sufí" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein" },
  { text: "La compasión es una curación poderosa.", author: "Dalai Lama" },
  { text: "Vivir es la cosa más rara del mundo. La mayoría de la gente existe, eso es todo.", author: "Oscar Wilde" },
  { text: "No hay camino para la felicidad: la felicidad es el camino.", author: "Buda" },
  { text: "El secreto del cambio es enfocar toda tu energía no en luchar contra lo viejo, sino en construir lo nuevo.", author: "Sócrates" },
  { text: "Ama a los que te odian, reza por los que te insultan. Es el único camino de superación.", author: "Mahatma Gandhi" },
  { text: "Lo que se puede imaginar, se puede crear.", author: "Anónimo" },
  { text: "El universo te dará lo que más temes o lo que más amas. Depende de cuál sea más fuerte.", author: "Proverbio espiritual" },
  { text: "La Yourt no es un lugar, es un estado mental.", author: "Proverbio" },
  { text: "El secreto de la vida es no tener secretos. No tengas nada que esconder.", author: "Eckhart Tolle" },
  { text: "La vida es un 90% actitud y 10% aptitud.", author: "Zig Ziglar" },
  { text: "Las palabras son la sombra de los pensamientos.", author: "Proverbio" },
  { text: "No es lo que te pasa, sino cómo lo tomas lo que importa.", author: "Epicteto" },
  { text: "La verdadera espiritualidad está en vivir el momento presente.", author: "Thich Nhat Hanh" },
  { text: "Cuando el disciple está listo, el maestro aparece.", author: "Proverbio budista" },
  { text: "El silencio del alma produce la paz interior que refleja la verdadera naturaleza del ser.", author: "Anónimo" },
  { text: "La gratitud es la memoria del corazón.", author: "Proverbio" },
  { text: "La sabiduría no viene de la edad, sino de la educación y el aprendizaje.", author: "Antón Chéjov" },
  { text: "Cuando cambias la forma en que miras las cosas, las cosas que miras cambian.", author: "Wayne Dyer" },
  { text: "No puedes controlar el viento, pero puedes ajustar las velas.", author: "Proverbio" },
  { text: "La perfección no existe, pero hay que acercarse a ella cada día.", author: "Coco Chanel" },
  { text: "El que vence a los demás es fuerte, el que se vence a sí mismo es todopoderoso.", author: "Lao Tse" },
  { text: "La santé no es un lujo. Es un derecho.", author: "Anónimo" },
  { text: "No hay mal que por bien no venga.", author: "Proverbio español" },
  { text: "El alma que nunca ha experimentado un día de lluvia no puede apreciar el arcoíris.", author: "Proverbio" },
  { text: "La esperanza es la última que se pierde.", author: "Proverbio español" },
  { text: "El que pregunta es tonto por cinco minutos, el que no pregunta es tonto para siempre.", author: "Proverbio chino" },
  { text: "No dejes para mañana lo que puedes hacer hoy.", author: "Proverbio" },
  { text: "La unión hace la fuerza.", author: "Proverbio" },
  { text: "El que la sigue la consigue.", author: "Proverbio español" },
  { text: "Más vale tarde que nunca.", author: "Proverbio" },
  { text: "A buen entendedor, pocas palabras bastan.", author: "Proverbio" },
  { text: "Dime con quién andas y te diré quién eres.", author: "Proverbio español" },
  { text: "En el silencio de la noche, el alma se conecta con el universo.", author: "Anónimo" },
  { text: "El yoga no es tocar los pies. Es lo que aprendes en el camino al doblarte.", author: "Jigar Gor" },
  { text: "La reiki es el arte de canalizar energía universal para sanar el cuerpo, la mente y el alma.", author: "Mikao Usui" },
  { text: "Las constelaciones revelan las lealtades invisibles que nos mantienen atrapados.", author: "Bert Hellinger" },
  { text: "El tarot es un espejo del alma, no una bola de cristal.", author: "Anónimo" },
  { text: "Los astros no dictan tu destino, pero iluminan tu camino.", author: "Proverbio astrológico" },
  { text: "El sonido cura porque recuerda a las células su frecuencia original.", author: "Proverbio de sanación" },
  { text: "La tierra tiene música para quien la escucha.", author: "George Santayana" },
  { text: "Flor de bach es el lenguaje de las flores para el alma herida.", author: "Edward Bach" },
  { text: "Cada vela encendida es una intención elevada al universo.", author: "Anónimo" },
  { text: "El tarot no predice el futuro, revela el presente.", author: "Anónimo" },
  { text: "La energía no se crea ni se destruye, se transforma.", author: "Ley de la termodinámica" },
  { text: "Tu cuerpo habla, escúchalo antes de que tenga que gritar.", author: "Anónimo" },
  { text: "La sanación comienza cuando das permiso para sentir.", author: "Anónimo" },
  { text: "No hay herida que el tiempo y el amor no puedan sanar.", author: "Proverbio" },
  { text: "Cada chakra es una puerta hacia una versión más alta de ti mismo.", author: "Anónimo" },
  { text: "La naturaleza es el mejor terapeuta.", author: "Proverbio" },
  { text: "El reiki no reemplaza la medicina, la complementa con amor.", author: "Anónimo" },
  { text: "Las emociones son energía en movimiento. Déjalas fluir.", author: "Anónimo" },
  { text: "La meditación no es pensar en nada, es estar en todo.", author: "Thich Nhat Hanh" },
  { text: "Cada exhalación es una oportunidad para soltar lo que ya no sirve.", author: "Anónimo" },
  { text: "El biomagnetismo reequilibra lo que la medicina no alcanza a ver.", author: "Dr. Isaac Goiz" },
  { text: "Una sesión de reiki puede cambiar el rumbo de tu semana entera.", author: "Anónimo" },
  { text: "Las piedras y cristales guardan la memoria de la tierra.", author: "Proverbio" },
  { text: "El incienso limpia el espacio como la oración limpia el alma.", author: "Proverbio" },
  { text: "Cada ceremonia es un acto de amor hacia la vida.", author: "Anónimo" },
  { text: "El retiro esparcial es donde la vida te enseña lo que el ruido te impide escuchar.", author: "Anónimo" },
  { text: "La ecodanza es liberar al cuerpo de lo que la mente ha acumulado.", author: "Anónimo" },
  { text: "Los cuencos tibetanos no solo suenan, recuerdan a tu cuerpo su frecuencia natural.", author: "Anónimo" },
  { text: "Cada sesión es una semilla. La transformación llega con el tiempo.", author: "Anónimo" },
  { text: "El crecimiento personal no tiene punto final, solo puntos de inflexión.", author: "Anónimo" },
  { text: "Hipnotizar es guiar al inconsciente hacia la sanación que ya sabe cómo ocurrir.", author: "Anónimo" },
  { text: "La nutrición consciente es alimentar el cuerpo con intención, no solo con comida.", author: "Anónimo" },
  { text: "El coaching espiritual no te dice qué hacer, te ayuda a escuchar lo que ya sabes.", author: "Anónimo" },
  { text: "Los registros akáshicos son la biblioteca del alma. Cada vida es un libro abierto.", author: "Anónimo" },
  { text: "Las barras de Access limpian el energymental como una ducha para el alma.", author: "Anónimo" },
  { text: "El pranayama enseña que el aliento es la llave de toda sanación.", author: "Proverbio yoga" },
  { text: "Cuando respiras conscientemente, le dices al cuerpo que estás seguro.", author: "Anónimo" },
  { text: "El chi kung es mover la energía como el río mueve la piedra: con paciencia.", author: "Proverbio" },
  { text: "Tai chi es la danza del equilibrio entre fuerza y suavidad.", author: "Proverbio" },
  { text: "El péndulo revela lo que los ojos no ven pero el alma intuye.", author: "Anónimo" },
  { text: "Cada wounded es un portal hacia una versión más completa de ti mismo.", author: "Anónimo" },
  { text: "La regresión a vidas pasadas no es viajar al pasado, es sanar el presente.", author: "Anónimo" },
  { text: "El chamanismo es el camino más antiguo de sanación de la humanidad.", author: "Proverbio" },
  { text: "Los mediums son puentes entre dos mundos, no portales de miedo.", author: "Anónimo" },
  { text: "La numerología revela los patrones ocultos que guían tu vida.", author: "Pitágoras" },
  { text: "Las runas no son adivinación, son sabiduría ancestral en símbolos.", author: "Proverbio nórdico" },
  { text: "El ocultismo no es oscuridad, es conocimiento profundo de lo invisible.", author: "Proverbio" },
  { text: "Los viajes iniciáticos transforman al viajero más que al destino.", author: "Proverbio" },
  { text: "El solsticio es el momento en que la tierra respira más profundamente.", author: "Anónimo" },
  { text: "Cada ritual es una puerta entre lo que eres y lo que puedes ser.", author: "Anónimo" },
  { text: "La ceremonia del cacao abre el corazón más que cualquier palabra.", author: "Proverbio maya" },
]
