export interface DemoProfessional {
  id: string
  name: string
  title: string
  bio: string
  specialties: string[]
  pricePerSession: number
  city: string
  rating: number
  reviews: number
  image?: string
  category: string
}

export interface DemoCourse {
  id: string
  title: string
  instructor: string
  description: string
  price: number
  lessons: number
  duration: string
  category: string
  image?: string
}

export interface DemoMeditation {
  id: string
  title: string
  instructor: string
  duration: string
  description: string
  category: string
}

export interface DemoEvent {
  id: string
  title: string
  organizer: string
  date: string
  location: string
  price: number
  description: string
  category: string
  type: "retiro" | "taller" | "ceremonia" | "formacion" | "feria" | "mercado" | "encuentro" | "circulo" | "charla"
  endDate?: string
  city?: string
}

export interface DemoPodcast {
  id: string
  title: string
  host: string
  duration: string
  description: string
  episodes: number
  category: string
  isTop: boolean
}

export interface DemoActivity {
  id: string
  name: string
  instructor: string
  type: string
  description: string
  schedule: string
  location: string
  price: number
  category: string
}

export function getDailyPhrase(): { text: string; author: string } {
  const phrases = [
    { text: "El despertar no es cambiar quién eres, sino recordar quién eres realmente.", author: "Siddhartha Gautama" },
    { text: "La paz viene de dentro. No la busques fuera.", author: "Buda" },
    { text: "El universo no es más que un gran eco. Todo lo que das, vuelve.", author: "Proverbio espiritual" },
    { text: "No hay camino hacia la paz, la paz es el camino.", author: "Mahatma Gandhi" },
    { text: "Conócete a ti mismo y conocerás el universo y los dioses.", author: "Sócrates" },
    { text: "Lo único que te impide obtener lo que deseas es la historia que te cuentas a ti mismo.", author: "Don Miguel Ruiz" },
    { text: "La conciencia es el campo donde todo ocurre. Eres ese campo.", author: "Eckhart Tolle" },
    { text: "Cuando te das cuenta de que nada te falta, el mundo entero te pertenece.", author: "Lao Tse" },
    { text: "No eres una gota en el océano. Eres el océano entero en una gota.", author: "Rumi" },
    { text: "La danza entre la oscuridad y la luz es lo que te hace despertar.", author: "Deepak Chopra" },
    { text: "El corazón es el faro del alma. Síguelo siempre.", author: "Proverbio sufí" },
    { text: "Tu vibración atrae tu realidad. Elévate.", author: "Anónimo" },
    { text: "No se trata de encontrar la salida, sino de ver que nunca estuviste encerrado.", author: "Mooji" },
    { text: "Cada persona que cruza tu camino tiene una lección que enseñarte. El despertar está en aprenderla.", author: "Osho" },
  ]
  const day = new Date().getDate()
  return phrases[day % phrases.length]
}

export const DEMO_PROFESSIONALS: DemoProfessional[] = [
  {
    id: "demo-pro-1",
    name: "Luna Martínez",
    title: "Maestra de Yoga Kundalini",
    bio: "Guía de yoga kundalini y meditación con 15 años de experiencia. Ayudo a despertar la energía vital a través de la respiración, el movimiento y el mantra.",
    specialties: ["Yoga Kundalini", "Meditación", "Mantras", "Respiración"],
    pricePerSession: 5000,
    city: "Barcelona",
    rating: 5,
    reviews: 28,
    category: "yoga",
  },
  {
    id: "demo-pro-2",
    name: "Santiago Vega",
    title: "Profesor de Hatha Yoga",
    bio: "El yoga como camino de autoconocimiento. Clases suaves y profundas para conectar con tu cuerpo y tu esencia.",
    specialties: ["Hatha Yoga", "Yoga Terapéutico", "Meditación"],
    pricePerSession: 3500,
    city: "Madrid",
    rating: 4.8,
    reviews: 19,
    category: "yoga",
  },
  {
    id: "demo-pro-3",
    name: "Maestro Rei Kenji",
    title: "Maestro de Reiki Usui",
    bio: "Maestro de Reiki Usui Tradicional. Ofrezco sesiones, iniciaciones y formaciones completas hasta nivel maestría.",
    specialties: ["Reiki Usui", "Reiki Karuna", "Sesiones", "Formaciones"],
    pricePerSession: 6000,
    city: "Valencia",
    rating: 5,
    reviews: 34,
    category: "reiki",
  },
  {
    id: "demo-pro-4",
    name: "Aisha Nuru",
    title: "Terapeuta Holística",
    bio: "Integro constelaciones familiares, flores de Bach y biomagnetismo para sanar el alma a nivel profundo.",
    specialties: ["Constelaciones", "Flores de Bach", "Biomagnetismo", "Sanación"],
    pricePerSession: 7000,
    city: "Online",
    rating: 4.9,
    reviews: 42,
    category: "terapias",
  },
  {
    id: "demo-pro-5",
    name: "Maya Shri",
    title: "Guía de Meditación y Mindfulness",
    bio: "Guía de meditación Vipassana y Mindfulness. Facilito espacios de silencio y presencia para encontrar la paz interior.",
    specialties: ["Meditación Vipassana", "Mindfulness", "Respiración Consciente", "Silencio"],
    pricePerSession: 4000,
    city: "Ibiza",
    rating: 4.9,
    reviews: 31,
    category: "meditacion",
  },
  {
    id: "demo-pro-6",
    name: "Ángel Luz",
    title: "Facilitador de Crecimiento Personal",
    bio: "Acompaño procesos de transformación personal a través de talleres vivenciales, coaching espiritual y ceremonias de planta.",
    specialties: ["Crecimiento Personal", "Coaching Espiritual", "Talleres", "Ceremonias"],
    pricePerSession: 5500,
    city: "Granada",
    rating: 4.7,
    reviews: 15,
    category: "crecimiento",
  },
  {
    id: "demo-pro-7",
    name: "Naturaleza Viva Retiros",
    title: "Organizadora de Retiros Espirituales",
    bio: "Creo experiencias de retiro en plena naturaleza para desconectar del ruido y reconectar con tu esencia.",
    specialties: ["Retiros", "Naturaleza", "Yoga", "Meditación", "Ayuno"],
    pricePerSession: 0,
    city: "Sierra Nevada",
    rating: 5,
    reviews: 22,
    category: "retiros",
  },
  {
    id: "demo-pro-8",
    name: "Krishna Das",
    title: "Terapeuta de Sonido",
    bio: "Sanación a través del sonido. Cuencos tibetanos, gongs, mantras y música devocional para equilibrar los chakras.",
    specialties: ["Cuencos Tibetanos", "Gong", "Mantras", "Sound Healing"],
    pricePerSession: 4500,
    city: "Barcelona",
    rating: 4.8,
    reviews: 17,
    category: "terapias",
  },
  {
    id: "demo-pro-9",
    name: "Sara Shanti",
    title: "Profesora de Yoga Integral",
    bio: "Yoga integral para todas las edades y niveles. Clases dinámicas y espirituales que nutren cuerpo, mente y alma.",
    specialties: ["Yoga Integral", "Yoga Nidra", "Meditación", "Pranayama"],
    pricePerSession: 3000,
    city: "Sevilla",
    rating: 4.9,
    reviews: 36,
    category: "yoga",
  },
  {
    id: "demo-pro-10",
    name: "Tara Devi",
    title: "Maestra de Meditación Trascendental",
    bio: "Enseño Meditación Trascendental y técnicas avanzadas de expansión de conciencia. 20 años de práctica en ashrams de la India.",
    specialties: ["Meditación Trascendental", "Mindfulness", "Filosofía Védica"],
    pricePerSession: 6500,
    city: "Online",
    rating: 5,
    reviews: 48,
    category: "meditacion",
  },
  {
    id: "demo-pro-11",
    name: "Maestro Li Chen",
    title: "Guía de Tai Chi y Chi Kung",
    bio: "30 años de práctica en artes marciales internas. Enseño Tai Chi estilo Yang, Chi Kung terapéutico y meditación en movimiento.",
    specialties: ["Tai Chi", "Chi Kung", "Meditación en Movimiento", "Artes Marciales Internas"],
    pricePerSession: 4000,
    city: "Barcelona",
    rating: 4.9,
    reviews: 33,
    category: "actividades",
  },
]

export const DEMO_COURSES: DemoCourse[] = [
  {
    id: "demo-course-1",
    title: "Yoga para Despertar la Conciencia",
    instructor: "Luna Martínez",
    description: "Curso completo de 8 semanas con sesiones de yoga kundalini, meditaciones guiadas y enseñanzas espirituales para elevar tu vibración.",
    price: 8900,
    lessons: 24,
    duration: "8 semanas",
    category: "yoga",
  },
  {
    id: "demo-course-2",
    title: "Reiki Nivel I, II y Maestría",
    instructor: "Maestro Rei Kenji",
    description: "Formación completa de Reiki Usui. Desde la iniciación hasta el nivel de maestría. Incluye manuales y certificados.",
    price: 29700,
    lessons: 12,
    duration: "3 meses",
    category: "reiki",
  },
  {
    id: "demo-course-3",
    title: "Autoconocimiento a través de las Constelaciones",
    instructor: "Aisha Nuru",
    description: "Curso teórico-práctico de constelaciones familiares para sanar tu árbol genealógico y liberar patrones heredados.",
    price: 14700,
    lessons: 10,
    duration: "6 semanas",
    category: "terapias",
  },
  {
    id: "demo-course-4",
    title: "Mindfulness y Meditación para la Vida Diaria",
    instructor: "Maya Shri",
    description: "Aprende a meditar y llevar el mindfulness a tu día a día. Reduce el estrés, mejora tu concentración y encuentra paz interior.",
    price: 5900,
    lessons: 16,
    duration: "8 semanas",
    category: "meditacion",
  },
  {
    id: "demo-course-5",
    title: "Despertar Espiritual: Guía Práctica",
    instructor: "Ángel Luz",
    description: "Un viaje de 30 días hacia tu despertar espiritual. Ejercicios, meditaciones y enseñanzas para expandir tu conciencia.",
    price: 7900,
    lessons: 30,
    duration: "30 días",
    category: "crecimiento",
  },
  {
    id: "demo-course-6",
    title: "Sanación con Cuencos Tibetanos",
    instructor: "Krishna Das",
    description: "Aprende el arte de la sanación con cuencos tibetanos. Técnicas de masaje sonoro, equilibrado de chakras y meditación con sonido.",
    price: 9900,
    lessons: 8,
    duration: "4 semanas",
    category: "terapias",
  },
  {
    id: "demo-course-7",
    title: "Yoga Nidra: El Sueño Consciente",
    instructor: "Sara Shanti",
    description: "Sumérgete en la práctica del yoga nidra, la meditación del sueño consciente. Relajación profunda y regeneración celular.",
    price: 4500,
    lessons: 12,
    duration: "4 semanas",
    category: "yoga",
  },
  {
    id: "demo-course-8",
    title: "Flores de Bach: Sanación Emocional",
    instructor: "Aisha Nuru",
    description: "Aprende a usar las 38 esencias florales de Bach para equilibrar tus emociones y sanar conflictos internos.",
    price: 6900,
    lessons: 10,
    duration: "5 semanas",
    category: "terapias",
  },
  {
    id: "demo-course-9",
    title: "Tai Chi para la Salud y la Longevidad",
    instructor: "Maestro Li Chen",
    description: "Aprende la forma de Tai Chi estilo Yang. Mejora tu equilibrio, vitalidad y conexión cuerpo-mente.",
    price: 7500,
    lessons: 16,
    duration: "8 semanas",
    category: "actividades",
  },
  {
    id: "demo-course-10",
    title: "Bio-danza: El Arte de Vivir",
    instructor: "Valeria Luna",
    description: "Sumérgete en la bio-danza y descubre cómo el movimiento consciente puede transformar tu vida.",
    price: 5900,
    lessons: 10,
    duration: "5 semanas",
    category: "actividades",
  },
  {
    id: "demo-course-11",
    title: "Acupuntura para el Dolor Crónico",
    instructor: "Dr. Javier Montes",
    description: "Curso teórico-práctico sobre puntos de acupuntura para tratar dolores crónicos de espalda, cervicales, rodillas y cabeza.",
    price: 9900,
    lessons: 12,
    duration: "6 semanas",
    category: "medicina",
  },
  {
    id: "demo-course-12",
    title: "Ayurveda: La Ciencia de la Vida",
    instructor: "Ananda Ayurveda",
    description: "Introducción completa al Ayurveda. Aprende tu constitución (dosha), alimentación, rutinas diarias y tratamientos de desintoxicación.",
    price: 7900,
    lessons: 16,
    duration: "8 semanas",
    category: "medicina",
  },
  {
    id: "demo-course-13",
    title: "Introducción al Estudio de la Torá",
    instructor: "Rabino David Cohen",
    description: "Curso completo de iniciación al estudio de la Torá. Desde el Génesis hasta el Deuteronomio, con enfoque en el significado espiritual y la tradición rabínica.",
    price: 8900,
    lessons: 20,
    duration: "10 semanas",
    category: "tradiciones",
  },
  {
    id: "demo-course-14",
    title: "Los Evangelios: Historia, Contexto y Espiritualidad",
    instructor: "Dr. Mateo Ávila",
    description: "Estudio profundo de los cuatro evangelios canónicos. Contexto histórico, análisis textual y enseñanza espiritual para la vida contemporánea.",
    price: 7900,
    lessons: 16,
    duration: "8 semanas",
    category: "tradiciones",
  },
  {
    id: "demo-course-15",
    title: "El Libro de los Muertos Egipcio: Guía del Más Allá",
    instructor: "Dr. Anubis Amón",
    description: "Traducción y estudio de los textos funerarios egipcios. Los hechizos, las fórmulas y el viaje del alma en el más allá según la tradición del Kemet.",
    price: 9900,
    lessons: 14,
    duration: "7 semanas",
    category: "ancestral",
  },
  {
    id: "demo-course-16",
    title: "Textos Sumerios: El Origen de la Civilización",
    instructor: "Ziauddin Enki",
    description: "Lectura y análisis de las tablillas cuneiformes sumerias. El Enuma Elish, Gilgamesh, la creación del hombre y los misterios de los Anunnaki.",
    price: 9900,
    lessons: 18,
    duration: "9 semanas",
    category: "ancestral",
  },
  {
    id: "demo-course-17",
    title: "Numerología Sagrada: El Lenguaje de los Números",
    instructor: "Maestro Pythagoras Nova",
    description: "Aprende a calcular e interpretar los números de tu vida: número de nacimiento, destino, alma y personalidad. La numerología como herramienta de autoconocimiento.",
    price: 6900,
    lessons: 12,
    duration: "6 semanas",
    category: "hermetismo",
  },
  {
    id: "demo-course-18",
    title: "Introducción a la Cábala Práctica",
    instructor: "David Ben-Shalom",
    description: "Fundamentos de la Cábala: el Árbol de la Vida, las 10 sefirot, los 22 senderos y la meditación cabalística. Un curso para aplicar la sabiduría mística en tu vida.",
    price: 9900,
    lessons: 16,
    duration: "8 semanas",
    category: "hermetismo",
  },
  {
    id: "demo-course-19",
    title: "Baños de Sonido: Formación Completa",
    instructor: "Ariel Tempus",
    description: "Aprende a facilitar baños de gong, cuencos tibetanos y diapasones. Protocolos para sesiones individuales y grupales, seguridad vibracional y la ciencia del sonido como terapia.",
    price: 15000,
    lessons: 20,
    duration: "10 semanas",
    category: "sonido",
  },
  {
    id: "demo-course-20",
    title: "Comunicación Animal: El Puente entre Especies",
    instructor: "Yara Manada",
    description: "Desarrolla tu capacidad innata de comunicación intuitiva con animales. Técnicas de telepatía, conexión emocional, constelaciones con animales y sanación del vínculo humano-animal.",
    price: 12000,
    lessons: 16,
    duration: "8 semanas",
    category: "animales",
  },
  {
    id: "demo-course-21",
    title: "Biohacking para el Despertar",
    instructor: "Axel Optimus",
    description: "Optimiza tu cuerpo y mente con biohacking, exposición al frío, fotobiomodulación, nootrópicos naturales y salud cuántica. Transforma tu biología desde la conciencia.",
    price: 18000,
    lessons: 24,
    duration: "12 semanas",
    category: "biohacking",
  },
  {
    id: "demo-course-22",
    title: "Facilitador de Breathwork y Respiración Holotrópica",
    instructor: "Prana Aliento",
    description: "Certificación completa para guiar sesiones de respiración holotrópica, breathwork y pranayama. Aprende a crear espacios seguros y facilitar transformaciones profundas.",
    price: 20000,
    lessons: 30,
    duration: "16 semanas",
    category: "respiracion",
  },
  {
    id: "demo-course-23",
    title: "Nutrición de Alta Vibración",
    instructor: "Vega Verde",
    description: "Transforma tu alimentación y tu vida. Bases de nutrición holística, veganismo consciente, superalimentos, detox guiado y cocina de alta vibración para elevar tu energía.",
    price: 11000,
    lessons: 18,
    duration: "9 semanas",
    category: "nutricion",
  },
]

export const DEMO_MEDITATIONS: DemoMeditation[] = [
  {
    id: "demo-med-1",
    title: "Meditación Guiada para Abrir el Corazón",
    instructor: "Maya Shri",
    duration: "15 min",
    description: "Una meditación suave para conectar con la energía del corazón y cultivar la compasión.",
    category: "meditacion",
  },
  {
    id: "demo-med-2",
    title: "Respiración Kundalini para Activar la Energía",
    instructor: "Luna Martínez",
    duration: "21 min",
    description: "Técnica de respiración kundalini para despertar la energía dormida en la base de la columna.",
    category: "yoga",
  },
  {
    id: "demo-med-3",
    title: "Meditación del Atardecer",
    instructor: "Sara Shanti",
    duration: "20 min",
    description: "Meditación guiada al atardecer para soltar el día y conectar con la gratitud.",
    category: "meditacion",
  },
  {
    id: "demo-med-4",
    title: "Mantra OM: Vibración Primordial",
    instructor: "Krishna Das",
    duration: "30 min",
    description: "Cántico del mantra OM con cuencos tibetanos para alinear tus chakras y elevar tu vibración.",
    category: "terapias",
  },
  {
    id: "demo-med-5",
    title: "Meditación para la Sanación Interior",
    instructor: "Maestro Rei Kenji",
    duration: "25 min",
    description: "Meditación guiada con símbolos de Reiki para sanar heridas emocionales y equilibrar la energía.",
    category: "reiki",
  },
  {
    id: "demo-med-6",
    title: "Yoga Nidra para Dormir Profundamente",
    instructor: "Sara Shanti",
    duration: "35 min",
    description: "Relajación guiada de yoga nidra para inducir un sueño profundo y reparador.",
    category: "yoga",
  },
  {
    id: "demo-med-7",
    title: "Meditación de los 7 Chakras",
    instructor: "Tara Devi",
    duration: "40 min",
    description: "Recorrido meditativo por los siete chakras principales con visualizaciones y mantras.",
    category: "meditacion",
  },
  {
    id: "demo-med-8",
    title: "Respiración Consciente para la Ansiedad",
    instructor: "Maya Shri",
    duration: "10 min",
    description: "Ejercicios de respiración consciente para calmar la ansiedad y volver al presente.",
    category: "meditacion",
  },
  {
    id: "demo-med-9",
    title: "Meditación de Conexión con la Tierra",
    instructor: "Naturaleza Viva Retiros",
    duration: "20 min",
    description: "Meditación guiada para enraizarte y conectar con la energía sanadora de la tierra.",
    category: "retiros",
  },
  {
    id: "demo-med-10",
    title: "Auto-Reiki: Sanación con las Manos",
    instructor: "Maestro Rei Kenji",
    duration: "15 min",
    description: "Práctica guiada de auto-reiki para armonizar tu energía en cualquier momento del día.",
    category: "reiki",
  },
  {
    id: "demo-med-11",
    title: "Chi Kung de los 5 Elementos",
    instructor: "Maestro Li Chen",
    duration: "20 min",
    description: "Secuencia de Chi Kung para armonizar los cinco elementos y equilibrar tu energía vital.",
    category: "actividades",
  },
  {
    id: "demo-med-12",
    title: "Meditación en Movimiento: Danza Libre",
    instructor: "Mónica Paz",
    duration: "25 min",
    description: "Una meditación guiada a través del movimiento libre y la danza consciente.",
    category: "actividades",
  },
  {
    id: "demo-med-13",
    title: "Baño de Gong: Viaje Sonoro Interior",
    instructor: "Ariel Tempus",
    duration: "45 min",
    description: "Meditación profunda guiada por las vibraciones del gong y los cuencos tibetanos. Un viaje sonoro que te lleva a estados expandidos de conciencia.",
    category: "sonido",
  },
  {
    id: "demo-med-14",
    title: "Conexión con tu Animal de Poder",
    instructor: "Yara Manada",
    duration: "20 min",
    description: "Meditación guiada para conectar con tu animal de poder, recibir su mensaje y sanar a través de la sabiduría animal.",
    category: "animales",
  },
  {
    id: "demo-med-15",
    title: "Respiración Guiada Wim Hof",
    instructor: "Max Frecuencia",
    duration: "15 min",
    description: "Sesión guiada de respiración del Método Wim Hof. Tres rondas de respiración potente y retención para oxigenar tu cuerpo y expandir tu energía.",
    category: "biohacking",
  },
  {
    id: "demo-med-16",
    title: "Holotrópica Guiada: Expansión de Conciencia",
    instructor: "Prana Aliento",
    duration: "60 min",
    description: "Sesión completa de respiración holotrópica guiada con música. Una experiencia profunda de sanación y expansión de la conciencia a través del aliento.",
    category: "respiracion",
  },
  {
    id: "demo-med-17",
    title: "Gratitud y Alimentación Consciente",
    instructor: "Vega Verde",
    duration: "10 min",
    description: "Meditación de gratitud antes de comer para conectar con la conciencia de los alimentos, bendecir tu comida y elevar la vibración de cada bocado.",
    category: "nutricion",
  },
]

export const DEMO_EVENTS: DemoEvent[] = [
  {
    id: "demo-ev-1",
    title: "Retiro de Silencio y Meditación",
    organizer: "Maya Shri",
    date: "15-20 Junio 2026",
    location: "Ibiza",
    price: 45000,
    description: "5 días de silencio, meditación y conexión profunda en un entorno natural privilegiado.",
    category: "retiros",
    type: "retiro",
  },
  {
    id: "demo-ev-2",
    title: "Taller de Constelaciones Familiares",
    organizer: "Aisha Nuru",
    date: "3-4 Mayo 2026",
    location: "Barcelona",
    price: 12000,
    description: "Taller intensivo de constelaciones familiares para sanar tu sistema familiar.",
    category: "terapias",
    type: "taller",
  },
  {
    id: "demo-ev-3",
    title: "Ceremonia de Cacao y Yoga bajo la Luna",
    organizer: "Luna Martínez",
    date: "28 Abril 2026",
    location: "Barcelona",
    price: 2500,
    description: "Ceremonia de cacao sagrado seguida de yoga y meditación bajo la luz de la luna llena.",
    category: "yoga",
    type: "ceremonia",
  },
  {
    id: "demo-ev-4",
    title: "Formación de Reiki Usui Nivel I",
    organizer: "Maestro Rei Kenji",
    date: "10-12 Mayo 2026",
    location: "Valencia",
    price: 15000,
    description: "Iniciación al Reiki Usui Nivel I. Incluye manual, certificado y prácticas supervisadas.",
    category: "reiki",
    type: "formacion",
  },
  {
    id: "demo-ev-5",
    title: "Retiro de Yoga y Ayurveda",
    organizer: "Naturaleza Viva Retiros",
    date: "1-8 Julio 2026",
    location: "Sierra Nevada",
    price: 65000,
    description: "Una semana de yoga, meditación, alimentación ayurvédica y baños de bosque.",
    category: "retiros",
    type: "retiro",
  },
  {
    id: "demo-ev-6",
    title: "Taller de Respiración Consciente",
    organizer: "Sara Shanti",
    date: "20 Mayo 2026",
    location: "Sevilla",
    price: 3500,
    description: "Aprende técnicas de respiración consciente para transformar tu energía y calmar tu mente.",
    category: "crecimiento",
    type: "taller",
  },
  {
    id: "demo-ev-7",
    title: "Círculo de Tai Chi al Amanecer",
    organizer: "Maestro Li Chen",
    date: "Cada sábado",
    location: "Parc de la Ciutadella, Barcelona",
    price: 1500,
    description: "Práctica grupal de Tai Chi al aire libre. Abierto a todos los niveles. Trae ropa cómoda.",
    category: "actividades",
    type: "taller",
  },
  {
    id: "demo-ev-8",
    title: "Encuentro de Bio-danza y Danza Circular",
    organizer: "Valeria Luna",
    date: "Último viernes de cada mes",
    location: "Centro Holístico Armonía, Madrid",
    price: 2000,
    description: "Encuentro mensual de bio-danza y danza circular para conectar con la comunidad y la alegría.",
    category: "actividades",
    type: "taller",
  },
  {
    id: "demo-ev-9",
    title: "Ecstatic Dance: Viaje de Movimiento y Música",
    organizer: "Mónica Paz",
    date: "15 Junio 2026",
    location: "Espacio Sagrado, Ibiza",
    price: 2500,
    description: "2 horas de danza libre y consciente con música en vivo. Una experiencia de conexión profunda.",
    category: "actividades",
    type: "ceremonia",
  },
  {
    id: "demo-ev-10",
    title: "Feria Holística de Primavera",
    organizer: "Asociación Holística Madrid",
    date: "24-26 Mayo 2026",
    location: "Pabellón de Cristal, Madrid",
    city: "Madrid",
    price: 800,
    description: "La mayor feria holística de Madrid con más de 80 expositores. Terapias, productos naturales, conferencias, talleres y demostraciones en vivo.",
    category: "zona",
    type: "feria",
  },
  {
    id: "demo-ev-11",
    title: "Mercado Esotérico de la Luna Nueva",
    organizer: "Colectivo Esotérico Barcelona",
    date: "7 Junio 2026",
    location: "Plaza del Sol, Barcelona",
    city: "Barcelona",
    price: 0,
    description: "Mercado al aire libre con puestos de tarot, cristales, inciensos, velas, libros esotéricos y lecturas de cartas. Entrada gratuita.",
    category: "zona",
    type: "mercado",
  },
  {
    id: "demo-ev-12",
    title: "Feria de la Brujería y el Ocultismo",
    organizer: "Círculo de la Sombra",
    date: "13-15 Junio 2026",
    location: "Ateneo Cultural, Valencia",
    city: "Valencia",
    price: 1200,
    description: "Tres días dedicados a la brujería tradicional, el ocultismo, grimorios antiguos, demonología y la figura de la Diosa Oscura. Conferencias, talleres y rituales.",
    category: "zona",
    type: "feria",
  },
  {
    id: "demo-ev-13",
    title: "Feria de Cristales, Piedras y Minerales",
    organizer: "Gemoterapia España",
    date: "17-18 Mayo 2026",
    location: "Hotel Auditorium, Madrid",
    city: "Madrid",
    price: 500,
    description: "Exposición y venta de cristales, piedras semipreciosas, minerales, fósiles y joyería energética. Expertos en gemoterapia resolverán tus dudas.",
    category: "zona",
    type: "feria",
  },
  {
    id: "demo-ev-14",
    title: "Círculo de Mujeres: Luna Llena en Sagitario",
    organizer: "Hermandad de la Luna",
    date: "30 Mayo 2026",
    location: "Centro Alma Femenina, Sevilla",
    city: "Sevilla",
    price: 1500,
    description: "Círculo sagrado de mujeres para conectar con la energía de la luna llena. Meditación, tambor, cánticos, intención compartida y hermandad.",
    category: "zona",
    type: "circulo",
  },
  {
    id: "demo-ev-15",
    title: "Mercado de Terapias Alternativas y Productos Naturales",
    organizer: "Vida Sana Eventos",
    date: "8 Junio 2026",
    location: "Parque del Retiro, Madrid",
    city: "Madrid",
    price: 0,
    description: "Mercado mensual con terapeutas, vendedores de productos ecológicos, alimentación consciente, cosmética natural y demostraciones de terapias.",
    category: "zona",
    type: "mercado",
  },
  {
    id: "demo-ev-16",
    title: "Charla: Los Evangelios Apócrifos y el Jesús Gnóstico",
    organizer: "Helena Sophia",
    date: "22 Mayo 2026",
    location: "Online / Zoom",
    city: "Online",
    price: 1000,
    description: "Conferencia online sobre los evangelios apócrifos de Nag Hammadi, el Jesús gnóstico y las enseñanzas secretas del cristianismo primitivo.",
    category: "zona",
    type: "charla",
  },
  {
    id: "demo-ev-17",
    title: "Feria de la Medicina Natural y la Herbolaria",
    organizer: "Centro de Salud Holística",
    date: "21-22 Junio 2026",
    location: "Feria de Muestras, Valladolid",
    city: "Valladolid",
    price: 600,
    description: "Feria dedicada a la medicina natural, fitoterapia, herboristería, aceites esenciales y alimentación viva. Talleres prácticos y consultas gratuitas.",
    category: "zona",
    type: "feria",
  },
  {
    id: "demo-ev-18",
    title: "Encuentro de Cánticos Devocionales y Mantras",
    organizer: "Krishna Das",
    date: "Primer sábado de cada mes",
    location: "Centro de Yoga Shanti, Barcelona",
    city: "Barcelona",
    price: 1000,
    description: "Encuentro mensual de kirtan, cánticos devocionales y mantras. Abierto a todos. Trae tu instrumento si quieres o solo ven a cantar.",
    category: "zona",
    type: "encuentro",
  },
  {
    id: "demo-ev-19",
    title: "Baño de Gong y Cuencos: Concierto Vibracional",
    organizer: "Ariel Tempus",
    date: "Cada luna llena",
    location: "Sala de Meditación Luz Interior, Barcelona",
    city: "Barcelona",
    price: 2500,
    description: "Experiencia inmersiva de baño de sonido con gong, cuencos tibetanos y de cristal, diapasones y canto armónico. Una noche de sanación vibracional bajo la luz de la luna llena.",
    category: "sonido",
    type: "ceremonia",
  },
  {
    id: "demo-ev-20",
    title: "Taller de Comunicación con Animales",
    organizer: "Yara Manada",
    date: "14-15 Junio 2026",
    location: "Centro Holístico El Refugio, Girona",
    city: "Girona",
    price: 8000,
    description: "Taller intensivo de comunicación intuitiva con animales. Aprende a conectar telepáticamente con perros, gatos, caballos y cualquier ser animal. Ejercicios prácticos y constelaciones con animales.",
    category: "animales",
    type: "taller",
  },
  {
    id: "demo-ev-21",
    title: "Retiro de Biohacking y Salud Cuántica",
    organizer: "Axel Optimus",
    date: "10-14 Septiembre 2026",
    location: "Finca de Retiros El Olivo, Valencia",
    city: "Valencia",
    price: 55000,
    description: "5 días de inmersión en biohacking: crioterapia, sauna infrarroja, fotobiomodulación, grounding, ayuno intermitente, nootrópicos naturales y meditaciones guiadas. Transforma tu biología.",
    category: "biohacking",
    type: "retiro",
  },
  {
    id: "demo-ev-22",
    title: "Círculo de Respiración Holotrópica",
    organizer: "Prana Aliento",
    date: "Todos los sábados",
    location: "Espacio Shakti, Barcelona",
    city: "Barcelona",
    price: 2000,
    description: "Sesiones semanales de respiración holotrópica en grupo. Música, trabajo corporal y proceso de integración. Abierto a todos los niveles. Trae tu esterilla y una intención.",
    category: "respiracion",
    type: "circulo",
  },
  {
    id: "demo-ev-23",
    title: "Taller de Cocina Consciente y Nutrición Holística",
    organizer: "Savia Tierra",
    date: "5-6 Julio 2026",
    location: "Escuela de Cocina Natural, Valencia",
    city: "Valencia",
    price: 7500,
    description: "Aprende a cocinar platos veganos de alta vibración. Raw food, macrobiótica, fermentados, germinados y técnicas de cocina consciente. Incluye degustación y recetario.",
    category: "nutricion",
    type: "taller",
  },
  {
    id: "demo-ev-24",
    title: "Ceremonia de Ayuno y Conexión con la Tierra",
    organizer: "Jason Ayuno",
    date: "21-23 Agosto 2026",
    location: "Cabañas en la Naturaleza, Sierra de Gredos",
    city: "Ávila",
    price: 35000,
    description: "Retiro de ayuno guiado de 3 días en plena naturaleza. Agua, infusiones, meditaciones al amanecer, baños de bosque y ceremonias de conexión con la tierra. Purifica cuerpo y alma.",
    category: "nutricion",
    type: "retiro",
  },
]

export const DEMO_PODCASTS: DemoPodcast[] = [
  {
    id: "demo-pod-1",
    title: "El Despertar de la Conciencia",
    host: "Luna Martínez",
    duration: "45 min",
    description: "Conversaciones semanales sobre espiritualidad, yoga y crecimiento personal. Invitados especiales y enseñanzas prácticas.",
    episodes: 128,
    category: "yoga",
    isTop: true,
  },
  {
    id: "demo-pod-2",
    title: "Reiki y Sanación Energética",
    host: "Maestro Rei Kenji",
    duration: "30 min",
    description: "Todo sobre Reiki, sanación energética y cómo elevar tu vibración a través de la energía universal.",
    episodes: 64,
    category: "reiki",
    isTop: true,
  },
  {
    id: "demo-pod-3",
    title: "Mindfulness para tu Día a Día",
    host: "Maya Shri",
    duration: "20 min",
    description: "Píldoras diarias de mindfulness y meditación para integrar la atención plena en tu rutina.",
    episodes: 256,
    category: "meditacion",
    isTop: true,
  },
  {
    id: "demo-pod-4",
    title: "Terapias Holísticas: El Poder de Sanar",
    host: "Aisha Nuru",
    duration: "50 min",
    description: "Exploramos constelaciones, flores de Bach, biomagnetismo y todas las terapias alternativas.",
    episodes: 89,
    category: "terapias",
    isTop: true,
  },
  {
    id: "demo-pod-5",
    title: "Camino Espiritual: Conversaciones con el Alma",
    host: "Ángel Luz",
    duration: "40 min",
    description: "Entrevistas profundas con buscadores espirituales, maestros y facilitadores de despertar.",
    episodes: 73,
    category: "crecimiento",
    isTop: true,
  },
  {
    id: "demo-pod-6",
    title: "Cuerpo en Movimiento: Tai Chi y Chi Kung",
    host: "Maestro Li Chen",
    duration: "25 min",
    description: "Prácticas guiadas de Tai Chi, Chi Kung y meditación en movimiento para tu salud física y espiritual.",
    episodes: 52,
    category: "actividades",
    isTop: true,
  },
  {
    id: "demo-pod-7",
    title: "Danza y Espiritualidad",
    host: "Valeria Luna",
    duration: "35 min",
    description: "La danza como camino de conexión espiritual. Bio-danza, danza circular y movimiento consciente.",
    episodes: 41,
    category: "actividades",
    isTop: false,
  },
  {
    id: "demo-pod-8",
    title: "Retiros que Transforman",
    host: "Naturaleza Viva Retiros",
    duration: "55 min",
    description: "Historias y experiencias de retiros espirituales alrededor del mundo. Inspiración para tu próximo viaje interior.",
    episodes: 37,
    category: "retiros",
    isTop: false,
  },
  {
    id: "demo-pod-9",
    title: "Música Devocional y Mantras",
    host: "Krishna Das",
    duration: "60 min",
    description: "Programa semanal de música devocional, mantras, cuencos tibetanos y sound healing.",
    episodes: 95,
    category: "terapias",
    isTop: false,
  },
  {
    id: "demo-pod-10",
    title: "Yoga Nidra y Relajación Profunda",
    host: "Sara Shanti",
    duration: "30 min",
    description: "Sesiones guiadas de yoga nidra, relajación profunda y meditación del sueño consciente.",
    episodes: 118,
    category: "yoga",
    isTop: false,
  },
  {
    id: "demo-pod-11",
    title: "La Senda de la Sombra",
    host: "Astaroth Blackwood",
    duration: "50 min",
    description: "Exploración profunda del ocultismo, la magia ceremonial y la tradición esotérica occidental. Grimorios, sellos, invocaciones y el camino de la mano izquierda.",
    episodes: 67,
    category: "ocultismo",
    isTop: true,
  },
  {
    id: "demo-pod-12",
    title: "Rituales Prohibidos",
    host: "Lilith Nocturna",
    duration: "45 min",
    description: "Historia del satanismo, magia negra y rituales de poder. Desde la tradición laveyana hasta el satanismo teísta y las corrientes ocultas contemporáneas.",
    episodes: 43,
    category: "ocultismo",
    isTop: true,
  },
  {
    id: "demo-pod-13",
    title: "El Libro de la Sombra",
    host: "Morgana Le Fay",
    duration: "40 min",
    description: "Wicca, brujería tradicional y neopaganismo. Prácticas de la Rueda del Año, herbología mágica, rituales de la luna y el arte de la hechicería natural.",
    episodes: 89,
    category: "ocultismo",
    isTop: true,
  },
  {
    id: "demo-pod-14",
    title: "Demonios y Ángeles Caídos",
    host: "Dr. Carmín Sombra",
    duration: "55 min",
    description: "Demonología, angelología oscura y la caída de Lucifer. Estudio de grimorios como La Llave de Salomón, el Ars Goetia y la jerarquía demoníaca.",
    episodes: 52,
    category: "ocultismo",
    isTop: true,
  },
  {
    id: "demo-pod-15",
    title: "La Llave de Salomón",
    host: "Enoc Mathers",
    duration: "60 min",
    description: "Magia ritual, grimorios y tradiciones ocultas. Análisis detallado de la Clavícula de Salomón, la Cábala práctica y la magia enoquiana.",
    episodes: 38,
    category: "ocultismo",
    isTop: false,
  },
  {
    id: "demo-pod-16",
    title: "Cultos y Sectas: El Lado Oscuro de la Fe",
    host: "Iván de la Cruz",
    duration: "70 min",
    description: "Análisis de cultos ocultistas, sectas satánicas y grupos esotéricos radicales a lo largo de la historia. Manipulación, poder y creencias extremas.",
    episodes: 46,
    category: "ocultismo",
    isTop: false,
  },
  {
    id: "demo-pod-17",
    title: "El Otro Lado",
    host: "Médium Azrael",
    duration: "35 min",
    description: "Mediumnidad, espiritismo, contacto con entidades y comunicación con los muertos. Sesiones espiritistas, ouija y fenómenos paranormales.",
    episodes: 74,
    category: "ocultismo",
    isTop: false,
  },
  {
    id: "demo-pod-18",
    title: "Lucifer: Luz y Sombra",
    host: "Dr. Ángel Luzbel",
    duration: "50 min",
    description: "La figura de Lucifer en el ocultismo, la teología y la cultura. Desde el portador de luz hasta el príncipe de las tinieblas. Una mirada sin prejuicios.",
    episodes: 31,
    category: "ocultismo",
    isTop: false,
  },
]

export const DEMO_ACTIVITIES: DemoActivity[] = [
  {
    id: "demo-act-1",
    name: "Grupo de Yoga al Amanecer",
    instructor: "Gabriel Sol",
    type: "Yoga Grupal",
    description: "Clases de yoga al aire libre en la playa al amanecer. Todos los niveles bienvenidos.",
    schedule: "Lun, Mié, Vie 6:30-7:30",
    location: "Playa de la Malvarrosa, Valencia",
    price: 1200,
    category: "actividades",
  },
  {
    id: "demo-act-2",
    name: "Tai Chi en el Parque",
    instructor: "Maestro Li Chen",
    type: "Tai Chi",
    description: "Práctica grupal de Tai Chi estilo Yang. Mejora tu equilibrio, flexibilidad y paz interior.",
    schedule: "Sáb 8:00-9:30",
    location: "Parc de la Ciutadella, Barcelona",
    price: 1000,
    category: "actividades",
  },
  {
    id: "demo-act-3",
    name: "Círculo de Bio-danza",
    instructor: "Valeria Luna",
    type: "Bio-danza",
    description: "Encuentro semanal de bio-danza para conectar con tu cuerpo, tus emociones y la comunidad.",
    schedule: "Jue 19:00-21:00",
    location: "Centro Holístico Armonía, Madrid",
    price: 1500,
    category: "actividades",
  },
  {
    id: "demo-act-4",
    name: "Ecstatic Dance Ibiza",
    instructor: "Mónica Paz",
    type: "Danza Consciente",
    description: "2 horas de danza libre con DJ en vivo. Un viaje de movimiento, música y conexión espiritual.",
    schedule: "Sáb 18:00-20:00",
    location: "Espacio Sagrado, Ibiza",
    price: 1800,
    category: "actividades",
  },
  {
    id: "demo-act-5",
    name: "Chi Kung Matutino",
    instructor: "Maestro Li Chen",
    type: "Chi Kung",
    description: "Práctica diaria de Chi Kung para activar la energía vital y empezar el día con vitalidad.",
    schedule: "Lun a Vie 7:00-7:45",
    location: "Online / Zoom",
    price: 800,
    category: "actividades",
  },
  {
    id: "demo-act-6",
    name: "Danza Circular de la Luna",
    instructor: "Valeria Luna",
    type: "Danza Circular",
    description: "Círculo de danza circular en conexión con los ciclos lunares. Mujeres y hombres bienvenidos.",
    schedule: "Una vez al mes (luna llena)",
    location: "Centro de la Tierra, Madrid",
    price: 1000,
    category: "actividades",
  },
  {
    id: "demo-act-7",
    name: "Yoga para Embarazadas",
    instructor: "Sara Shanti",
    type: "Yoga Terapéutico",
    description: "Yoga suave y consciente para embarazadas. Preparación física y emocional para el parto.",
    schedule: "Mar y Jue 17:00-18:15",
    location: "Estudio Shanti, Sevilla",
    price: 1400,
    category: "actividades",
  },
  {
    id: "demo-act-8",
    name: "Yoga Familiar en la Naturaleza",
    instructor: "Gabriel Sol",
    type: "Yoga Grupal",
    description: "Yoga para toda la familia. Niños y adultos practican juntos en plena naturaleza.",
    schedule: "Dom 10:00-11:15",
    location: "Parque Natural de la Albufera, Valencia",
    price: 2000,
    category: "actividades",
  },
]

export const CATEGORIES = [
  // ── Zona ──
  {
    id: "zona",
    name: "En tu Zona",
    icon: "⊙",
    description: "Ferias, mercados, charlas y encuentros espirituales cerca de ti",
    longDescription: "Descubre todos los eventos, ferias, mercados esotéricos, círculos y encuentros que suceden en tu zona. Desde la Feria Holística de Madrid hasta el Mercado Esotérico de Barcelona, pasando por charlas online, círculos de mujeres y encuentros de mantras. También encontrarás aquí todos los profesionales de la app cerca de ti, organizados por ciudad, para que puedas conocer quién está en tu zona.",
    keywords: ["feria", "mercado", "círculo", "circulo", "encuentro", "charla", "evento local", "cerca de ti", "zona", "ciudad"],
    color: "from-green-500/20 to-emerald-500/5",
    borderColor: "border-green-500/30",
    textColor: "text-green-300",
    bgColor: "bg-green-500/10",
    gradient: "from-green-900/40 via-emerald-900/20 to-transparent",
  },
  // ── Podcasts ──
  {
    id: "podcasts",
    name: "Top Podcasts Espirituales",
    icon: "♪",
    description: "Podcasts recomendados sobre espiritualidad, yoga, meditación y crecimiento",
    longDescription: "La mejor selección de podcasts sobre espiritualidad, yoga, meditación, crecimiento personal, terapias alternativas y desarrollo de la conciencia. Episodios semanales con expertos, enseñanzas prácticas y conversaciones profundas para nutrir tu alma en cualquier momento y lugar.",
    keywords: [],
    color: "from-pink-500/20 to-fuchsia-500/5",
    borderColor: "border-pink-500/30",
    textColor: "text-pink-300",
    bgColor: "bg-pink-500/10",
    gradient: "from-pink-900/40 via-fuchsia-900/20 to-transparent",
  },

  // ── DESPERTAR DEL CUERPO ──
  {
    id: "yoga",
    name: "Yoga",
    icon: "☉",
    description: "Clases, profesores y cursos de yoga para despertar tu energía",
    longDescription: "Aquí encontrarás profesores de todos los estilos: Hatha, Vinyasa, Kundalini, Ashtanga, Iyengar, Yoga Nidra y más. También cursos de formación, clases presenciales y online, y sesiones individuales. El yoga es una disciplina que integra posturas físicas (asanas), respiración (pranayama), meditación y filosofía para equilibrar cuerpo, mente y espíritu.",
    keywords: ["yoga", "kundalini", "hatha", "ashtanga", "vinyasa", "iyengar", "nidra", "pranayama", "clase"],
    color: "from-amber-500/20 to-orange-500/5",
    borderColor: "border-amber-500/30",
    textColor: "text-amber-300",
    bgColor: "bg-amber-500/10",
    gradient: "from-amber-900/40 via-purple-900/20 to-transparent",
  },
  {
    id: "reiki",
    name: "Reiki",
    icon: "✴",
    description: "Sesiones, cursos y formaciones de Reiki",
    longDescription: "El Reiki es una técnica de sanación energética de origen japonés que canaliza la energía universal a través de las manos. Aquí encontrarás maestros de Reiki Usui, Karuna Reiki y otras líneas, que ofrecen sesiones de sanación, iniciaciones y formaciones completas desde nivel I hasta maestría.",
    keywords: ["reiki", "usui", "karuna", "sanación"],
    color: "from-violet-500/20 to-purple-500/5",
    borderColor: "border-violet-500/30",
    textColor: "text-violet-300",
    bgColor: "bg-violet-500/10",
    gradient: "from-violet-900/40 via-purple-900/20 to-transparent",
  },
  {
    id: "tai-chi",
    name: "Tai Chi",
    icon: "☯",
    description: "Clases y maestros de Tai Chi, movimiento y energía",
    longDescription: "El Tai Chi es un arte marcial interno chino que combina movimientos lentos y fluidos con respiración profunda y meditación en movimiento. También conocido como Tai Chi Chuan, esta práctica milenaria mejora el equilibrio, la flexibilidad y la circulación de la energía vital (chi).",
    keywords: ["tai chi", "taichi", "tai chi chuan", "movimiento", "energía"],
    color: "from-teal-500/20 to-cyan-500/5",
    borderColor: "border-teal-500/30",
    textColor: "text-teal-300",
    bgColor: "bg-teal-500/10",
    gradient: "from-teal-900/40 via-emerald-900/20 to-transparent",
  },
  {
    id: "bio-danza",
    name: "Bio-danza",
    icon: "◈",
    description: "Sesiones de Bio-danza, danza consciente y movimiento integrativo",
    longDescription: "La Bio-danza es un sistema de integración humana basado en la danza, la música y el movimiento. Creada por Rolando Toro, busca conectar con la vida a través de ejercicios que integran el cuerpo, las emociones y la espiritualidad en un espacio seguro y grupal.",
    keywords: ["bio-danza", "biodanza", "danza consciente", "danza", "movimiento integrativo"],
    color: "from-rose-400/20 to-pink-500/5",
    borderColor: "border-rose-400/30",
    textColor: "text-rose-300",
    bgColor: "bg-rose-400/10",
    gradient: "from-rose-900/40 via-pink-900/20 to-transparent",
  },
  {
    id: "chi-kung",
    name: "Chi Kung",
    icon: "◈",
    description: "Chi Kung, Qigong, energía vital y movimiento consciente",
    longDescription: "El Chi Kung (o Qigong) es una antigua práctica china que integra posturas suaves, respiración y concentración mental para cultivar y equilibrar la energía vital (chi). Con raíces en la medicina tradicional china y las artes marciales internas, es una herramienta poderosa para la salud y la longevidad.",
    keywords: ["chi kung", "qigong", "qi gong", "energía vital", "chi", "movimiento"],
    color: "from-cyan-500/20 to-sky-500/5",
    borderColor: "border-cyan-500/30",
    textColor: "text-cyan-300",
    bgColor: "bg-cyan-500/10",
    gradient: "from-cyan-900/40 via-sky-900/20 to-transparent",
  },
  {
    id: "ecstatic-dance",
    name: "Ecstatic Dance",
    icon: "⟐",
    description: "Ecstatic dance, danza libre y movimiento expansivo",
    longDescription: "Ecstatic Dance es una práctica de danza libre y consciente donde no hay pasos coreografiados ni juicios. Simplemente te dejas llevar por la música y permites que tu cuerpo se mueva desde la libertad más absoluta. Una experiencia catártica de conexión, expresión y celebración.",
    keywords: ["ecstatic dance", "ecstatic", "danza libre", "danza expansiva", "movimiento libre"],
    color: "from-fuchsia-500/20 to-purple-500/5",
    borderColor: "border-fuchsia-500/30",
    textColor: "text-fuchsia-300",
    bgColor: "bg-fuchsia-500/10",
    gradient: "from-fuchsia-900/40 via-purple-900/20 to-transparent",
  },
  {
    id: "barras-access",
    name: "Barras de Access",
    icon: "✦",
    description: "Sesiones y facilitadores de Barras de Access",
    longDescription: "Las Barras de Access son 32 puntos en la cabeza que, cuando se tocan suavemente, liberan las cargas electromagnéticas de todos los pensamientos, ideas, creencias y emociones que has ido almacenando a lo largo de tu vida. Una sesión de Barras puede generar cambios profundos con efectos que duran semanas.",
    keywords: ["barras de access", "barras access", "access consciousness", "toques", "liberación"],
    color: "from-indigo-500/20 to-violet-500/5",
    borderColor: "border-indigo-500/30",
    textColor: "text-indigo-300",
    bgColor: "bg-indigo-500/10",
    gradient: "from-indigo-900/40 via-violet-900/20 to-transparent",
  },
  {
    id: "nutricion",
    name: "Nutrición Consciente",
    icon: "⚘",
    description: "Ayuno, veganismo, alimentación espiritual, cocina consciente y nutrición holística",
    longDescription: "La alimentación como camino espiritual. Ayuno intermitente y prolongado, veganismo, alimentación vegetal, crudiveganismo, cocina consciente, nutrición holística, alimentos de alta vibración, superalimentos, detox y depuración. Nutrir el cuerpo es nutrir el alma. Descubre cómo la comida puede ser tu mejor medicina y tu práctica espiritual diaria.",
    keywords: ["ayuno", "vegano", "veganismo", "vegetal", "crudivegano", "nutrición", "nutricion", "alimentación", "alimentacion", "cocina consciente", "holístico", "holistico", "detox", "depuración", "depuracion", "superalimento", "alta vibración", "comida espiritual", "macrobiótica", "macrobiotica"],
    color: "from-lime-500/20 to-green-500/5",
    borderColor: "border-lime-500/30",
    textColor: "text-lime-300",
    bgColor: "bg-lime-500/10",
    gradient: "from-lime-900/40 via-green-900/20 to-transparent",
  },
  {
    id: "medicina",
    name: "Medicina Alternativa",
    icon: "⚕",
    description: "Acupuntura, reflexología, naturopatía, Ayurveda, flores de Bach, medicina china y homeopatía",
    longDescription: "Profesionales de la salud natural y la medicina complementaria: acupuntura, reflexología, osteopatía, naturopatía, Ayurveda, medicina tradicional china, homeopatía, fitoterapia, herbolaria y flores de Bach. Una visión integral de la salud que combina el conocimiento ancestral con la ciencia moderna para tratar cuerpo, mente y espíritu.",
    keywords: ["acupuntura", "reflexología", "reflexologia", "osteopatía", "osteopatia", "naturopatía", "naturopatia", "ayurveda", "homeopatía", "homeopatia", "medicina china", "fitoterapia", "herbolaria", "flores de bach", "flores bach"],
    color: "from-red-500/20 to-rose-500/5",
    borderColor: "border-red-500/30",
    textColor: "text-red-300",
    bgColor: "bg-red-500/10",
    gradient: "from-red-900/40 via-rose-900/20 to-transparent",
  },

  // ── DESPERTAR DEL ALMA ──
  {
    id: "meditacion",
    name: "Meditación & Mindfulness",
    icon: "◯",
    description: "Meditaciones guiadas, mindfulness y atención plena",
    longDescription: "Encuentra guías de meditación, instructores de mindfulness y maestros de atención plena. Desde meditación Vipassana y trascendental hasta meditaciones guiadas para reducir el estrés, la ansiedad y cultivar la paz interior. También incluye retiros de silencio, cursos de mindfulness y prácticas diarias.",
    keywords: ["meditación", "meditacion", "mindfulness", "atención plena", "vipassana", "trascendental"],
    color: "from-sky-500/20 to-blue-500/5",
    borderColor: "border-sky-500/30",
    textColor: "text-sky-300",
    bgColor: "bg-sky-500/10",
    gradient: "from-sky-900/40 via-indigo-900/20 to-transparent",
  },
  {
    id: "sonido",
    name: "Terapias de Sonido",
    icon: "♫",
    description: "Gong, cuencos, diapasones, biodanza sonora y sanación vibracional",
    longDescription: "El sonido como herramienta de sanación y transformación. Terapias con gong, cuencos tibetanos y de cristal, diapasones, mantras, canto armónico, biodanza sonora y baños de sonido. La vibración penetra en cada célula del cuerpo, liberando bloqueos, equilibrando el sistema nervioso y elevando la conciencia.",
    keywords: ["gong", "cuenco", "sonido", "vibración", "vibracion", "diapasón", "diapason", "baño de sonido", "baño sonoro", "canto armónico", "mantra", "biodanza sonora", "frecuencia", "432hz", "528hz"],
    color: "from-cyan-500/20 to-sky-500/5",
    borderColor: "border-cyan-500/30",
    textColor: "text-cyan-300",
    bgColor: "bg-cyan-500/10",
    gradient: "from-cyan-900/40 via-sky-900/20 to-transparent",
  },
  {
    id: "respiracion",
    name: "Respiración Consciente",
    icon: "☁",
    description: "Respiración holotrópica, breathwork, pranayama y técnicas de respiración para sanación",
    longDescription: "El poder transformador de la respiración consciente. Respiración holotrópica, breathwork, pranayama (yoga), rebirthing, respiración circular y técnicas de liberación emocional a través del aliento. Una de las herramientas más rápidas y efectivas para sanar traumas, expandir la conciencia y conectar con estados alterados de percepción.",
    keywords: ["respiración", "respiracion", "holotrópica", "holotropica", "breathwork", "pranayama", "rebirthing", "aliento", "respiración circular", "respiracion circular", "liberación emocional", "liberacion emocional", "wim hof"],
    color: "from-blue-500/20 to-indigo-500/5",
    borderColor: "border-blue-500/30",
    textColor: "text-blue-300",
    bgColor: "bg-blue-500/10",
    gradient: "from-blue-900/40 via-indigo-900/20 to-transparent",
  },
  {
    id: "animales",
    name: "Terapia con Animales",
    icon: "♡",
    description: "Comunicación animal, constelaciones con animales, terapias asistidas y despertar animal",
    longDescription: "El despertar de los animales: comunicación intuitiva con animales, constelaciones familiares con animales, terapias asistidas con perros, caballos, delfines y otros animales de poder. Facilitadores que conectan con la conciencia animal, sanan vínculos con nuestras mascotas y honran a los animales como guías espirituales.",
    keywords: ["animal", "mascota", "comunicación animal", "comunicacion animal", "constelaciones con animales", "terapia asistida", "delfín", "caballo", "perro", "animal de poder", "totem", "tótem", "conexión animal", "conexion animal"],
    color: "from-green-500/20 to-lime-500/5",
    borderColor: "border-green-500/30",
    textColor: "text-green-300",
    bgColor: "bg-green-500/10",
    gradient: "from-green-900/40 via-lime-900/20 to-transparent",
  },
  {
    id: "constelaciones",
    name: "Constelaciones Familiares",
    icon: "⚘",
    description: "Constelaciones familiares, terapia sistémica y transgeneracional",
    longDescription: "Las constelaciones familiares son un enfoque terapéutico creado por Bert Hellinger que revela las dinámicas ocultas en los sistemas familiares. A través de la representación espacial, se identifican lealtades invisibles, exclusiones y patrones que se repiten de generación en generación, permitiendo su sanación.",
    keywords: ["constelaciones", "constelacion familiar", "terapia sistémica", "sistemica", "transgeneracional", "hellinger"],
    color: "from-emerald-500/20 to-teal-500/5",
    borderColor: "border-emerald-500/30",
    textColor: "text-emerald-300",
    bgColor: "bg-emerald-500/10",
    gradient: "from-emerald-900/40 via-teal-900/20 to-transparent",
  },
  {
    id: "hipnosis",
    name: "Hipnosis Clínica y Regresiva",
    icon: "◐",
    description: "Hipnosis clínica, regresiva e hipnoterapia para sanación profunda",
    longDescription: "La hipnosis es un estado natural de conciencia enfocada que permite acceder al subconsciente para liberar traumas, creencias limitantes y bloqueos emocionales. La hipnosis regresiva permite explorar vidas pasadas y eventos del pasado que siguen influyendo en el presente.",
    keywords: ["hipnosis", "hipnoterapia", "regresiva", "vidas pasadas", "regresión", "regresion", "hipnósis"],
    color: "from-purple-800/40 to-indigo-900/20",
    borderColor: "border-purple-700/30",
    textColor: "text-purple-300",
    bgColor: "bg-purple-800/20",
    gradient: "from-purple-900/50 via-indigo-900/30 to-transparent",
  },
  {
    id: "crecimiento",
    name: "Crecimiento Personal",
    icon: "⟡",
    description: "Talleres, formaciones, coaching y desarrollo espiritual",
    longDescription: "Talleres, formaciones y sesiones para tu desarrollo personal y despertar espiritual. Aquí encontrarás coaches espirituales, facilitadores de transformación, guías de conciencia, intuición y desarrollo del potencial humano. Un espacio para explorar quién eres realmente y expandir tu potencial ilimitado.",
    keywords: ["crecimiento", "desarrollo", "taller", "holístico", "holistico", "espiritual", "conciencia", "transformación", "transformacion", "coaching", "intuición", "intuicion", "potencial"],
    color: "from-rose-500/20 to-pink-500/5",
    borderColor: "border-rose-500/30",
    textColor: "text-rose-300",
    bgColor: "bg-rose-500/10",
    gradient: "from-rose-900/40 via-purple-900/20 to-transparent",
  },
  {
    id: "limpieza-energetica",
    name: "Limpieza Energética y Chamanismo",
    icon: "☥",
    description: "Limpiezas energéticas, chamanismo, sanación chamánica y rituales",
    longDescription: "El chamanismo es la práctica espiritual más antigua de la humanidad. Los chamanes son guías que transitan entre mundos para traer sanación, sabiduría y equilibrio. Limpiezas energéticas, rituales de purificación, extracción de energías densas, ceremonias con plantas de poder y conexión con los reinos espirituales.",
    keywords: ["chamanismo", "chamán", "chaman", "limpieza energética", "limpieza energetica", "sanación chamánica", "sanacion chamanica", "ritual", "purificación", "purificacion", "plantas de poder"],
    color: "from-amber-800/40 to-yellow-900/20",
    borderColor: "border-amber-700/30",
    textColor: "text-amber-300",
    bgColor: "bg-amber-800/20",
    gradient: "from-amber-900/50 via-yellow-900/30 to-transparent",
  },

  // ── DESPERTAR DEL CONOCIMIENTO ──
  {
    id: "tradiciones",
    name: "Tradiciones Sagradas y Sabiduría Ancestral",
    icon: "☥",
    description: "Estudio de textos sagrados, hermetismo, sabiduría ancestral y tradiciones espirituales",
    longDescription: "El conocimiento sagrado de todas las épocas: estudio de la Torá, Talmud, Biblia, Evangelios y textos bíblicos con exégesis profunda; sabiduría de las civilizaciones antiguas (sumerios, egipcios, texto apócrifos, gnósticos); tradición hermética (Corpus Hermeticum, Tabla Esmeralda, alquimia espiritual); chamanismo y ceremonias indígenas. Un puente entre la erudición y la experiencia espiritual directa.",
    keywords: ["torá", "tora", "biblia", "evangelio", "evangelios", "exégesis", "exegesis", "rabino", "rabínico", "rabinico", "talmud", "sagrada escritura", "teología", "teologia", "pentateuco", "profetas", "sumerio", "egipcio", "apócrifo", "apocrifo", "gnóstico", "gnostico", "nag hammadi", "hermético", "hermetico", "corpus hermeticum", "alquimia", "hermetismo", "indígena", "indigena", "chamanismo", "prohibido", "gilgamesh", "anunnaki", "kemet"],
    color: "from-blue-800/40 to-indigo-900/20",
    borderColor: "border-blue-700/30",
    textColor: "text-blue-300",
    bgColor: "bg-blue-800/20",
    gradient: "from-blue-900/50 via-indigo-900/30 to-transparent",
  },
  {
    id: "cabala",
    name: "Cábala",
    icon: "✶",
    description: "Estudio de la Cábala, Árbol de la Vida, Zohar y mística judía",
    longDescription: "La Cábala es la tradición mística del judaísmo que revela la naturaleza de Dios, el universo y el alma humana. A través del estudio del Árbol de la Vida (sefirot), el Zohar, la gematría y las técnicas de meditación cabalística, se accede a los niveles más profundos de la realidad espiritual.",
    keywords: ["cábala", "cabala", "árbol de la vida", "arbol de la vida", "zohar", "sefirot", "gematría", "gematria", "temurá", "notaricón", "notaricon", "mística judía", "mistica judia"],
    color: "from-purple-800/40 to-fuchsia-900/20",
    borderColor: "border-purple-700/30",
    textColor: "text-purple-300",
    bgColor: "bg-purple-800/20",
    gradient: "from-purple-900/50 via-fuchsia-900/30 to-transparent",
  },
  {
    id: "numerologia",
    name: "Numerología",
    icon: "✶",
    description: "Numerología aplicada, pitagórica y cabalística para el autoconocimiento",
    longDescription: "La numerología es el estudio del significado esotérico de los números y su influencia en nuestra vida. Desde la numerología pitagórica que analiza tu fecha de nacimiento y nombre, hasta la numerología cabalística que desvela los patrones numéricos del universo. Una herramienta de autoconocimiento y predicción.",
    keywords: ["numerología", "numerologia", "pitagórica", "pitagorica", "número de vida", "numero de vida", "numerología aplicada", "numerologia aplicada"],
    color: "from-yellow-800/40 to-amber-900/20",
    borderColor: "border-yellow-700/30",
    textColor: "text-yellow-300",
    bgColor: "bg-yellow-800/20",
    gradient: "from-yellow-900/50 via-amber-900/30 to-transparent",
  },

  // ── DESPERTAR A LO DESCONOCIDO ──
  {
    id: "tarot",
    name: "Tarot, Runas y Métodos Adivinatorios",
    icon: "☆",
    description: "Tarot, runas, oráculos, I Ching y métodos de adivinación",
    longDescription: "Lectura de tarot terapéutico, runas nórdicas, oráculos, I Ching, quiromancia, radiestesia con péndulo y todas las artes adivinatorias. Profesionales que te ayudarán a encontrar claridad, propósito y dirección a través de las herramientas de percepción y autoconocimiento profundo.",
    keywords: ["tarot", "runas", "adivinación", "adivinacion", "oráculo", "oraculo", "cartas", "quiromancia", "péndulo", "pendulo", "i ching", "lectura de velas", "registro akáshico", "registro akashico"],
    color: "from-fuchsia-500/20 to-pink-500/5",
    borderColor: "border-fuchsia-500/30",
    textColor: "text-fuchsia-300",
    bgColor: "bg-fuchsia-500/10",
    gradient: "from-fuchsia-900/40 via-pink-900/20 to-transparent",
  },
  {
    id: "mediums",
    name: "Mediums",
    icon: "◇",
    description: "Mediumnidad, canalización y comunicación espiritual",
    longDescription: "Los médiums son personas con la capacidad de percibir y comunicarse con entidades espirituales, guías, ángeles y seres queridos fallecidos. Canalización de mensajes, comunicación con el más allá, desarrollo de la mediumnidad y conexión con planos superiores de conciencia.",
    keywords: ["medium", "mediumnidad", "canalización", "canalizacion", "espiritismo", "comunicación espiritual", "comunicacion espiritual", "médium", "entidades", "guías espirituales", "guias espirituales"],
    color: "from-violet-500/20 to-purple-500/5",
    borderColor: "border-violet-500/30",
    textColor: "text-violet-300",
    bgColor: "bg-violet-500/10",
    gradient: "from-violet-900/40 via-purple-900/20 to-transparent",
  },
  {
    id: "astrologia",
    name: "Astrología",
    icon: "☆",
    description: "Carta astral, astrología predictiva, sinastría y horóscopo",
    longDescription: "La astrología es el estudio de la influencia de los astros en la personalidad y el destino humano. Lectura de carta astral, astrología predictiva, sinastría de pareja, revoluciones solares, tránsitos y retornos. Descubre cómo los movimientos planetarios afectan tu vida y tu camino espiritual.",
    keywords: ["astrología", "astrologia", "carta astral", "carta natal", "horóscopo", "horoscopo", "sinastría", "sinastria", "tránsitos", "transitos", "revolución solar", "revolucion solar", "predictiva"],
    color: "from-indigo-500/20 to-blue-500/5",
    borderColor: "border-indigo-500/30",
    textColor: "text-indigo-300",
    bgColor: "bg-indigo-500/10",
    gradient: "from-indigo-900/40 via-blue-900/20 to-transparent",
  },

  // ── DESPERTAR DE LO OCULTO ──
  {
    id: "ocultismo",
    name: "Ocultismo",
    icon: "◐",
    description: "Podcasts sobre ocultismo, satanismo, demonología, brujería, grimorios y el lado oscuro de la espiritualidad",
    longDescription: "Un espacio dedicado a los podcasts que exploran el lado oscuro y oculto de la espiritualidad: ocultismo, satanismo, demonología, brujería tradicional y moderna (Wicca, neopaganismo), grimorios como La Llave de Salomón, cultos y sectas, espiritismo, ángeles caídos y la figura de Lucifer. Contenido para mentes curiosas sin prejuicios.",
    keywords: ["ocultismo", "satanismo", "demonología", "demonologia", "brujería", "brujeria", "grimorio", "magia negra", "wicca", "neopaganismo", "ángeles caídos", "angeles caidos", "llave de salomón", "salomon", "cultos", "sectas", "espiritismo", "lucifer"],
    color: "from-gray-800/40 to-zinc-900/20",
    borderColor: "border-gray-700/30",
    textColor: "text-gray-300",
    bgColor: "bg-gray-800/20",
    gradient: "from-gray-900/60 via-zinc-900/40 to-transparent",
  },

  // ── EXPERIENCIAS PARA DESPERTAR ──
  {
    id: "viajes",
    name: "Viajes Iniciáticos y Peregrinaciones",
    icon: "✦",
    description: "Peregrinaciones, viajes espirituales y retiros iniciáticos a lugares sagrados del mundo",
    longDescription: "Guias y organizadores de viajes con propósito: peregrinaciones a Tierra Santa, viajes iniciáticos a las pirámides de Egipto y los templos de Grecia, rutas espirituales por Machu Picchu, Sedona, el Tíbet y la Amazonía, el Camino de Santiago, ceremonias en lugares de poder y retiros en monasterios. Viaja para transformarte.",
    keywords: ["viaje iniciático", "viaje iniciatico", "peregrinación", "peregrinacion", "tierra santa", "lugares sagrados", "machu picchu", "tíbet", "tibet", "sedona", "piramides", "pirámides", "egipto", "peregrino", "ruta espiritual"],
    color: "from-cyan-800/40 to-teal-900/20",
    borderColor: "border-cyan-700/30",
    textColor: "text-cyan-300",
    bgColor: "bg-cyan-800/20",
    gradient: "from-cyan-900/50 via-teal-900/30 to-transparent",
  },
  {
    id: "retiros",
    name: "Retiros Espirituales",
    icon: "▲",
    description: "Retiros espirituales, ceremonias y eventos",
    longDescription: "Retiros espirituales, ceremonias, eventos presenciales y formaciones intensivas. Desde retiros de silencio en la naturaleza hasta ceremonias de luna llena, pasando por formaciones presenciales de fin de semana. Desconecta de la rutina y conéctate con tu esencia en entornos sagrados.",
    keywords: ["retiro", "evento", "ceremonia", "taller presencial", "naturaleza"],
    color: "from-orange-500/20 to-yellow-500/5",
    borderColor: "border-orange-500/30",
    textColor: "text-orange-300",
    bgColor: "bg-orange-500/10",
    gradient: "from-orange-900/40 via-amber-900/20 to-transparent",
  },
  {
    id: "ferias-eventos",
    name: "Ferias y Eventos Puntuales",
    icon: "⊙",
    description: "Ferias, mercados y eventos espirituales puntuales",
    longDescription: "Ferias holísticas, mercados esotéricos, encuentros y eventos puntuales donde conectar con la comunidad espiritual. Espacios para descubrir nuevos profesionales, productos y herramientas para tu camino de despertar.",
    keywords: ["feria", "mercado", "evento puntual", "encuentro", "feria holística", "mercado esotérico"],
    color: "from-yellow-500/20 to-amber-500/5",
    borderColor: "border-yellow-500/30",
    textColor: "text-yellow-300",
    bgColor: "bg-yellow-500/10",
    gradient: "from-yellow-900/40 via-amber-900/20 to-transparent",
  },
  {
    id: "ceremonias",
    name: "Ceremonias",
    icon: "▲",
    description: "Ceremonias espirituales, rituales y encuentros sagrados",
    longDescription: "Ceremonias de luna llena, rituales de paso, círculos de palabra, temazcales, ceremonias con cacao, ayahuasca, san pedro y otras plantas de poder. Espacios sagrados facilitados por guías experimentados para la expansión de la conciencia y la sanación profunda.",
    keywords: ["ceremonia", "ritual", "luna llena", "temazcal", "cacao", "ayahuasca", "san pedro", "plantas de poder", "círculo sagrado", "circulo sagrado"],
    color: "from-orange-800/40 to-red-900/20",
    borderColor: "border-orange-700/30",
    textColor: "text-orange-300",
    bgColor: "bg-orange-800/20",
    gradient: "from-orange-900/50 via-red-900/30 to-transparent",
  },

  // ── MATERIALES ──
  {
    id: "materiales",
    name: "Materiales para tu Despertar",
    icon: "◆",
    description: "Pulseras, amuletos, minerales, inciensos, velas, cuencos, libros y herbolaria",
    longDescription: "Todo lo que necesitas para tu práctica espiritual: pulseras energéticas y amuletos de protección, minerales y piedras, inciensos naturales, velas rituales, cojines de yoga y esterillas, cuencos tibetanos, alimentos conscientes y herbolaria, libros de espiritualidad, cartas de tarot y péndulos. Productos hechos con conciencia por artesanos y tiendas especializadas.",
    keywords: ["pulsera", "amuleto", "mineral", "piedra", "incienso", "vela", "cuenco", "cojín", "cojin", "esterilla", "libro espiritual", "herbolaria", "tarot", "péndulo", "pendulo", "alimento", "artesanía", "artesania"],
    color: "from-yellow-500/20 to-amber-500/5",
    borderColor: "border-yellow-500/30",
    textColor: "text-yellow-300",
    bgColor: "bg-yellow-500/10",
    gradient: "from-yellow-900/40 via-amber-900/20 to-transparent",
  },
]

export function getItemsByCategory(categoryId: string) {
  return {
    professionals: DEMO_PROFESSIONALS.filter((p) => p.category === categoryId),
    courses: DEMO_COURSES.filter((c) => c.category === categoryId),
    meditations: DEMO_MEDITATIONS.filter((m) => m.category === categoryId),
    events: DEMO_EVENTS.filter((e) => e.category === categoryId),
  }
}

export function getAllItems() {
  return {
    professionals: DEMO_PROFESSIONALS,
    courses: DEMO_COURSES,
    meditations: DEMO_MEDITATIONS,
    events: DEMO_EVENTS,
  }
}

export const CITY_COORDS: Record<string, [number, number]> = {
  Madrid: [40.4168, -3.7038],
  Barcelona: [41.3874, 2.1686],
  Valencia: [39.4699, -0.3763],
  Sevilla: [37.3891, -5.9845],
  Granada: [37.1773, -3.5986],
  "Sierra Nevada": [37.0969, -3.3953],
  Ibiza: [38.9067, 1.4206],
  Bilbao: [43.263, -2.935],
  "Palma de Mallorca": [39.5696, 2.6502],
  Málaga: [36.7213, -4.4214],
  Alicante: [38.3452, -0.481],
  Zaragoza: [41.6488, -0.8891],
  Murcia: [37.9922, -1.1307],
  "Las Palmas": [28.1248, -15.43],
  "Santa Cruz de Tenerife": [28.4682, -16.2546],
  Pamplona: [42.8125, -1.6458],
  "San Sebastián": [43.3183, -1.9812],
  "Santiago de Compostela": [42.8782, -8.5448],
  Toledo: [39.8628, -4.0273],
  Córdoba: [37.8882, -4.7794],
  Valladolid: [41.6523, -4.7245],
  Burgos: [42.344, -3.6969],
  Salamanca: [40.9701, -5.6635],
  "La Coruña": [43.3713, -8.418],
  Vigo: [42.2406, -8.7207],
  Gijón: [43.5322, -5.6611],
  Oviedo: [43.3619, -5.8494],
  Huelva: [37.2614, -6.9447],
  Almería: [36.8381, -2.4597],
  Cádiz: [36.5271, -6.2886],
  Jaén: [37.7796, -3.7849],
  León: [42.5987, -5.5671],
  Huesca: [42.1318, -0.4078],
  Teruel: [40.3457, -1.1064],
  Cuenca: [40.0681, -2.1348],
  Guadalajara: [40.6384, -3.1675],
  "Ciudad Real": [38.9862, -3.9292],
  Albacete: [38.9942, -1.8585],
  Badajoz: [38.8794, -6.9706],
  Cáceres: [39.4722, -6.3708],
  Logroño: [42.4627, -2.444],
  Soria: [41.7666, -2.4791],
  Segovia: [40.9429, -4.1088],
  Ávila: [40.656, -4.6995],
  Zamora: [41.5035, -5.7445],
  Palencia: [42.0096, -4.5285],
  Lugo: [43.0097, -7.5568],
  Ourense: [42.3358, -7.8639],
  Pontevedra: [42.431, -8.6443],
  Ceuta: [35.8883, -5.3162],
  Melilla: [35.2937, -2.9383],
  Online: [40.4168, -3.7038],
}
