export interface DemoProfessional {
  id: string
  name: string
  title: string
  bio: string
  specialties: string[]
  pricePerSession: number
  city: string
  rating: number
  reviews: number
  image?: string
  category: string
}

export interface DemoCourse {
  id: string
  title: string
  instructor: string
  description: string
  price: number
  lessons: number
  duration: string
  category: string
  image?: string
}

export interface DemoMeditation {
  id: string
  title: string
  instructor: string
  duration: string
  description: string
  category: string
}

export interface DemoEvent {
  id: string
  title: string
  organizer: string
  date: string
  location: string
  price: number
  description: string
  category: string
  type: "retiro" | "taller" | "ceremonia" | "formacion" | "feria" | "mercado" | "encuentro" | "circulo" | "charla"
  endDate?: string
  city?: string
}

export interface DemoPodcast {
  id: string
  title: string
  host: string
  duration: string
  description: string
  episodes: number
  category: string
  isTop: boolean
}

export interface DemoActivity {
  id: string
  name: string
  instructor: string
  type: string
  description: string
  schedule: string
  location: string
  price: number
  category: string
}

export function getDailyPhrase(): { text: string; author: string } {
  const phrases = [
    { text: "El despertar no es cambiar quién eres, sino recordar quién eres realmente.", author: "Siddhartha Gautama" },
    { text: "La paz viene de dentro. No la busques fuera.", author: "Buda" },
    { text: "El universo no es más que un gran eco. Todo lo que das, vuelve.", author: "Proverbio espiritual" },
    { text: "No hay camino hacia la paz, la paz es el camino.", author: "Mahatma Gandhi" },
    { text: "Conócete a ti mismo y conocerás el universo y los dioses.", author: "Sócrates" },
    { text: "Lo único que te impide obtener lo que deseas es la historia que te cuentas a ti mismo.", author: "Don Miguel Ruiz" },
    { text: "La conciencia es el campo donde todo ocurre. Eres ese campo.", author: "Eckhart Tolle" },
    { text: "Cuando te das cuenta de que nada te falta, el mundo entero te pertenece.", author: "Lao Tse" },
    { text: "No eres una gota en el océano. Eres el océano entero en una gota.", author: "Rumi" },
    { text: "La danza entre la oscuridad y la luz es lo que te hace despertar.", author: "Deepak Chopra" },
    { text: "El corazón es el faro del alma. Síguelo siempre.", author: "Proverbio sufí" },
    { text: "Tu vibración atrae tu realidad. Elévate.", author: "Anónimo" },
    { text: "No se trata de encontrar la salida, sino de ver que nunca estuviste encerrado.", author: "Mooji" },
    { text: "Cada persona que cruza tu camino tiene una lección que enseñarte. El despertar está en aprenderla.", author: "Osho" },
  ]
  const day = new Date().getDate()
  return phrases[day % phrases.length]
}

export const DEMO_PROFESSIONALS: DemoProfessional[] = [
  {
    id: "demo-pro-1",
    name: "Luna Martínez",
    title: "Maestra de Yoga Kundalini",
    bio: "Guía de yoga kundalini y meditación con 15 años de experiencia. Ayudo a despertar la energía vital a través de la respiración, el movimiento y el mantra.",
    specialties: ["Yoga Kundalini", "Meditación", "Mantras", "Respiración"],
    pricePerSession: 5000,
    city: "Barcelona",
    rating: 5,
    reviews: 28,
    category: "yoga",
  },
  {
    id: "demo-pro-2",
    name: "Santiago Vega",
    title: "Profesor de Hatha Yoga",
    bio: "El yoga como camino de autoconocimiento. Clases suaves y profundas para conectar con tu cuerpo y tu esencia.",
    specialties: ["Hatha Yoga", "Yoga Terapéutico", "Meditación"],
    pricePerSession: 3500,
    city: "Madrid",
    rating: 4.8,
    reviews: 19,
    category: "yoga",
  },
  {
    id: "demo-pro-3",
    name: "Maestro Rei Kenji",
    title: "Maestro de Reiki Usui",
    bio: "Maestro de Reiki Usui Tradicional. Ofrezco sesiones, iniciaciones y formaciones completas hasta nivel maestría.",
    specialties: ["Reiki Usui", "Reiki Karuna", "Sesiones", "Formaciones"],
    pricePerSession: 6000,
    city: "Valencia",
    rating: 5,
    reviews: 34,
    category: "reiki",
  },
  {
    id: "demo-pro-4",
    name: "Aisha Nuru",
    title: "Terapeuta Holística",
    bio: "Integro constelaciones familiares, flores de Bach y biomagnetismo para sanar el alma a nivel profundo.",
    specialties: ["Constelaciones", "Flores de Bach", "Biomagnetismo", "Sanación"],
    pricePerSession: 7000,
    city: "Online",
    rating: 4.9,
    reviews: 42,
    category: "terapias",
  },
  {
    id: "demo-pro-5",
    name: "Maya Shri",
    title: "Guía de Meditación y Mindfulness",
    bio: "Guía de meditación Vipassana y Mindfulness. Facilito espacios de silencio y presencia para encontrar la paz interior.",
    specialties: ["Meditación Vipassana", "Mindfulness", "Respiración Consciente", "Silencio"],
    pricePerSession: 4000,
    city: "Ibiza",
    rating: 4.9,
    reviews: 31,
    category: "meditacion",
  },
  {
    id: "demo-pro-6",
    name: "Ángel Luz",
    title: "Facilitador de Crecimiento Personal",
    bio: "Acompaño procesos de transformación personal a través de talleres vivenciales, coaching espiritual y ceremonias de planta.",
    specialties: ["Crecimiento Personal", "Coaching Espiritual", "Talleres", "Ceremonias"],
    pricePerSession: 5500,
    city: "Granada",
    rating: 4.7,
    reviews: 15,
    category: "crecimiento",
  },
  {
    id: "demo-pro-7",
    name: "Naturaleza Viva Retiros",
    title: "Organizadora de Retiros Espirituales",
    bio: "Creo experiencias de retiro en plena naturaleza para desconectar del ruido y reconectar con tu esencia.",
    specialties: ["Retiros", "Naturaleza", "Yoga", "Meditación", "Ayuno"],
    pricePerSession: 0,
    city: "Sierra Nevada",
    rating: 5,
    reviews: 22,
    category: "retiros",
  },
  {
    id: "demo-pro-8",
    name: "Krishna Das",
    title: "Terapeuta de Sonido",
    bio: "Sanación a través del sonido. Cuencos tibetanos, gongs, mantras y música devocional para equilibrar los chakras.",
    specialties: ["Cuencos Tibetanos", "Gong", "Mantras", "Sound Healing"],
    pricePerSession: 4500,
    city: "Barcelona",
    rating: 4.8,
    reviews: 17,
    category: "terapias",
  },
  {
    id: "demo-pro-9",
    name: "Sara Shanti",
    title: "Profesora de Yoga Integral",
    bio: "Yoga integral para todas las edades y niveles. Clases dinámicas y espirituales que nutren cuerpo, mente y alma.",
    specialties: ["Yoga Integral", "Yoga Nidra", "Meditación", "Pranayama"],
    pricePerSession: 3000,
    city: "Sevilla",
    rating: 4.9,
    reviews: 36,
    category: "yoga",
  },
  {
    id: "demo-pro-10",
    name: "Tara Devi",
    title: "Maestra de Meditación Trascendental",
    bio: "Enseño Meditación Trascendental y técnicas avanzadas de expansión de conciencia. 20 años de práctica en ashrams de la India.",
    specialties: ["Meditación Trascendental", "Mindfulness", "Filosofía Védica"],
    pricePerSession: 6500,
    city: "Online",
    rating: 5,
    reviews: 48,
    category: "meditacion",
  },
  {
    id: "demo-pro-11",
    name: "Maestro Li Chen",
    title: "Guía de Tai Chi y Chi Kung",
    bio: "30 años de práctica en artes marciales internas. Enseño Tai Chi estilo Yang, Chi Kung terapéutico y meditación en movimiento.",
    specialties: ["Tai Chi", "Chi Kung", "Meditación en Movimiento", "Artes Marciales Internas"],
    pricePerSession: 4000,
    city: "Barcelona",
    rating: 4.9,
    reviews: 33,
    category: "actividades",
  },
  {
    id: "demo-pro-12",
    name: "Valeria Luna",
    title: "Facilitadora de Bio-danza",
    bio: "Facilitadora de bio-danza y danza circular. Creo espacios de movimiento consciente para conectar con la alegría vital y la comunidad.",
    specialties: ["Bio-danza", "Danza Circular", "Movimiento Consciente", "Expresión Corporal"],
    pricePerSession: 2500,
    city: "Madrid",
    rating: 4.7,
    reviews: 21,
    category: "actividades",
  },
  {
    id: "demo-pro-13",
    name: "Gabriel Sol",
    title: "Instructor de Yoga al Aire Libre",
    bio: "Yoga en la naturaleza para conectar con los elementos. Grupos de yoga al amanecer en parques y playas.",
    specialties: ["Yoga Grupal", "Yoga al Aire Libre", "Yoga al Amanecer", "Respiración"],
    pricePerSession: 1500,
    city: "Valencia",
    rating: 4.8,
    reviews: 45,
    category: "actividades",
  },
  {
    id: "demo-pro-14",
    name: "Mónica Paz",
    title: "Guía de Danza Consciente",
    bio: "La danza como camino espiritual. Facilito círculos de danza libre, ecstatic dance y movement medicine.",
    specialties: ["Danza Consciente", "Ecstatic Dance", "Movement Medicine", "Círculos de Mujer"],
    pricePerSession: 2000,
    city: "Ibiza",
    rating: 4.9,
    reviews: 27,
    category: "actividades",
  },
  {
    id: "demo-pro-15",
    name: "Dr. Javier Montes",
    title: "Médico Acupuntor",
    bio: "Licenciado en medicina con 20 años de experiencia en acupuntura tradicional china. Trato problemas crónicos, dolores musculoesqueléticos y trastornos emocionales.",
    specialties: ["Acupuntura", "Moxibustión", "Digitopuntura", "Medicina China"],
    pricePerSession: 6000,
    city: "Madrid",
    rating: 4.9,
    reviews: 53,
    category: "medicina",
  },
  {
    id: "demo-pro-16",
    name: "Clara Valls",
    title: "Osteópata y Terapeuta Craneosacral",
    bio: "Osteópata especializada en terapia craneosacral, visceral y estructural. Trato dolores de espalda, migrañas y trastornos digestivos desde la raíz.",
    specialties: ["Osteopatía", "Craneosacral", "Terapia Visceral", "Reequilibrio Postural"],
    pricePerSession: 5500,
    city: "Barcelona",
    rating: 4.8,
    reviews: 37,
    category: "medicina",
  },
  {
    id: "demo-pro-17",
    name: "Ananda Ayurveda",
    title: "Médico Ayurvédico",
    bio: "Médico especializado en Ayurveda tradicional. Diagnóstico por pulso, tratamientos de Panchakarma, fitoterapia ayurvédica y consejo nutricional.",
    specialties: ["Ayurveda", "Panchakarma", "Fitoterapia", "Nutrición Ayurvédica", "Diagnóstico por Pulso"],
    pricePerSession: 7000,
    city: "Ibiza",
    rating: 5,
    reviews: 29,
    category: "medicina",
  },
  {
    id: "demo-pro-18",
    name: "Dra. Elena Ríos",
    title: "Especialista en Medicina China Tradicional",
    bio: "Doctora en Medicina Tradicional China. Fitoterapia china, acupuntura, tuina y recomendaciones de alimentación según los 5 elementos.",
    specialties: ["Medicina China", "Fitoterapia China", "Acupuntura", "Tuina", "Alimentación Energética"],
    pricePerSession: 6500,
    city: "Valencia",
    rating: 4.9,
    reviews: 41,
    category: "medicina",
  },
  {
    id: "demo-pro-19",
    name: "Marco Sanna",
    title: "Naturopata y Herbólogo",
    bio: "Naturopata especializado en fitoterapia, nutrición ortomolecular e iriología. Te ayudo a recuperar la salud de forma natural y sostenible.",
    specialties: ["Naturopatía", "Fitoterapia", "Nutrición Ortomolecular", "Iriología", "Desintoxicación"],
    pricePerSession: 5000,
    city: "Online",
    rating: 4.7,
    reviews: 34,
    category: "medicina",
  },
  {
    id: "demo-pro-20",
    name: "Centro de Salud Holística",
    title: "Centro de Medicina Alternativa",
    bio: "Centro multidisciplinar con profesionales de acupuntura, osteopatía, naturopatía, homeopatía y medicina china. Valoración integral.",
    specialties: ["Acupuntura", "Osteopatía", "Homeopatía", "Medicina China", "Naturopatía"],
    pricePerSession: 4500,
    city: "Sevilla",
    rating: 4.6,
    reviews: 68,
    category: "medicina",
  },
  {
    id: "demo-pro-21",
    name: "Isabella de la Cruz",
    title: "Tarotista y Astróloga Espiritual",
    bio: "Lectura de tarot terapéutico y carta astral con enfoque en sanación interior. Te ayudo a encontrar claridad, propósito y dirección a través de los arcanos y los astros.",
    specialties: ["Tarot Terapéutico", "Astrología Espiritual", "Lectura de Cartas", "Oráculos", "Numerología Sagrada"],
    pricePerSession: 4000,
    city: "Madrid",
    rating: 4.8,
    reviews: 45,
    category: "tarot",
  },
  {
    id: "demo-pro-22",
    name: "Héctor Mendoza",
    title: "Guía de Mediumnidad y Cábala",
    bio: "Facilitador de talleres de mediumnidad evolutiva y estudio de la Cábala. Te acompaño en el despertar de tu intuición y la conexión con planos superiores de conciencia. Formado en la tradición hermética.",
    specialties: ["Mediumnidad", "Cábala", "Despertar de la Intuición", "Conexión Espiritual", "Meditación Avanzada"],
    pricePerSession: 5500,
    city: "Barcelona",
    rating: 4.7,
    reviews: 33,
    category: "hermetismo",
  },
  {
    id: "demo-pro-23",
    name: "Selene Luna",
    title: "Astróloga Terapéutica",
    bio: "Astrología como herramienta de autoconocimiento y sanación. Realizo cartas natales, revoluciones solares y sinastrías con un enfoque terapéutico y compasivo.",
    specialties: ["Astrología Terapéutica", "Carta Natal", "Revolución Solar", "Sinastría", "Astrología Evolutiva"],
    pricePerSession: 4500,
    city: "Online",
    rating: 4.9,
    reviews: 57,
    category: "tarot",
  },
  {
    id: "demo-pro-43",
    name: "Madame Oráculo",
    title: "Vidente y Maestra de Runas",
    bio: "Vidente experta en runas nórdicas, lectura de velas, café y péndulo. Te ayudo a ver con claridad tu camino, tomar decisiones importantes y entender las señales del universo. 30 años de experiencia en artes adivinatorias.",
    specialties: ["Runas Nórdicas", "Lectura de Velas", "Péndulo", "Quiromancia", "Lectura de Café"],
    pricePerSession: 6000,
    city: "Barcelona",
    rating: 4.9,
    reviews: 73,
    category: "tarot",
  },
  {
    id: "demo-pro-44",
    name: "Luna de Fuego",
    title: "Tarotista Evolutiva y Canalizadora",
    bio: "Tarot terapéutico evolutivo, canalización de registros akáshicos y lectura de runas. Mi enfoque combina la sabiduría de los arcanos con la guía espiritual para ayudarte a desbloquear tu potencial y encontrar tu propósito.",
    specialties: ["Tarot Evolutivo", "Registros Akáshicos", "Runas", "Canalización", "Lectura de Vidas Pasadas"],
    pricePerSession: 7000,
    city: "Online",
    rating: 4.8,
    reviews: 51,
    category: "tarot",
  },
  {
    id: "demo-pro-45",
    name: "Adivino de Oriente",
    title: "Maestro de I Ching y Astrología China",
    bio: "Experto en I Ching (Libro de las Mutaciones), astrología china, feng shui y lectura del rostro (Mien Shiang). Consulta presencial y online para orientación en negocios, relaciones y desarrollo personal.",
    specialties: ["I Ching", "Astrología China", "Feng Shui", "Mien Shiang", "Bazi"],
    pricePerSession: 5500,
    city: "Madrid",
    rating: 4.7,
    reviews: 38,
    category: "tarot",
  },
  {
    id: "demo-pro-46",
    name: "Médium del Más Allá",
    title: "Médium y Canalizador Espiritual",
    bio: "Médium de contacto con seres fallecidos, guías espirituales y ángeles. Sesiones de canalización, mensajes de seres queridos traspasados y limpieza energética de espacios. Décadas de experiencia en el puente entre mundos.",
    specialties: ["Mediumnidad", "Canalización", "Contacto con Fallecidos", "Limpieza Energética", "Guías Espirituales"],
    pricePerSession: 6500,
    city: "Valencia",
    rating: 4.6,
    reviews: 44,
    category: "tarot",
  },
  {
    id: "demo-pro-47",
    name: "Selene de los Ángeles",
    title: "Quirómana y Astróloga",
    bio: "Lectura de líneas de la mano (quiromancia), carta astral completa y predicciones anuales. Te ayudo a descifrar el mapa de tu vida escrito en tus manos y en los astros para que tomes las riendas de tu destino.",
    specialties: ["Quiromancia", "Astrología Predictiva", "Cartas Astrales", "Predicciones Anuales", "Numerología del Destino"],
    pricePerSession: 5000,
    city: "Sevilla",
    rating: 4.8,
    reviews: 62,
    category: "tarot",
  },
  {
    id: "demo-pro-24",
    name: "David Ben-Shalom",
    title: "Maestro de Cábala y Mística Judía",
    bio: "Estudioso de la Cábala, el Zohar y el Árbol de la Vida. Ofrezco sesiones individuales y grupales de estudio de la mística judía con enfoque práctico para la vida cotidiana.",
    specialties: ["Cábala", "Árbol de la Vida", "Zohar", "Mística Judía", "Meditación Cabalística"],
    pricePerSession: 6000,
    city: "Valencia",
    rating: 5,
    reviews: 22,
    category: "hermetismo",
  },
  {
    id: "demo-pro-25",
    name: "Rabino David Cohen",
    title: "Maestro de Torá y Mística Judía",
    bio: "Rabino y estudioso de la Torá, el Talmud y la literatura rabínica. Ofrezco estudio profundo de las sagradas escrituras desde la tradición judía con enfoque espiritual y contemporáneo.",
    specialties: ["Torá", "Talmud", "Mística Judía", "Exégesis Bíblica", "Literatura Rabínica"],
    pricePerSession: 7000,
    city: "Jerusalén / Online",
    rating: 5,
    reviews: 48,
    category: "tradiciones",
  },
  {
    id: "demo-pro-26",
    name: "Dr. Mateo Ávila",
    title: "Teólogo y Exégeta Bíblico",
    bio: "Doctor en Teología y Estudios Bíblicos. Análisis profundo de los Evangelios, las cartas paulinas y el Apocalipsis desde una perspectiva histórica, simbólica y espiritual.",
    specialties: ["Evangelios", "Apocalipsis", "Exégesis", "Teología", "Historia Bíblica"],
    pricePerSession: 5500,
    city: "Madrid",
    rating: 4.8,
    reviews: 36,
    category: "tradiciones",
  },
  {
    id: "demo-pro-27",
    name: "Hermana Clara de Asís",
    title: "Maestra de Espiritualidad Cristiana",
    bio: "Guía de lectio divina y estudio contemplativo de los Evangelios. Te ayudo a conectar con la dimensión mística y transformadora de las sagradas escrituras.",
    specialties: ["Lectio Divina", "Evangelios", "Mística Cristiana", "Espiritualidad", "Oración Contemplativa"],
    pricePerSession: 4000,
    city: "Online",
    rating: 4.9,
    reviews: 29,
    category: "tradiciones",
  },
  {
    id: "demo-pro-28",
    name: "Dr. Anubis Amón",
    title: "Egiptólogo y Maestro de Misterios Antiguos",
    bio: "Especialista en textos egipcios antiguos, el Libro de los Muertos y los misterios de las pirámides. Te guío en el estudio de la sabiduría milenaria del Kemet.",
    specialties: ["Egiptología", "Libro de los Muertos", "Jeroglíficos", "Misterios Egipcios", "Filosofía de Kemet"],
    pricePerSession: 6500,
    city: "Online",
    rating: 4.9,
    reviews: 31,
    category: "ancestral",
  },
  {
    id: "demo-pro-29",
    name: "Ziauddin Enki",
    title: "Experto en Textos Sumerios y Acadios",
    bio: "Investigador de las tablillas cuneiformes sumerias y acadias. Estudio del Enuma Elish, la Epopeya de Gilgamesh y el origen de las civilizaciones antiguas de Mesopotamia.",
    specialties: ["Textos Sumerios", "Cuneiforme", "Epopeya de Gilgamesh", "Enuma Elish", "Mitología Mesopotámica"],
    pricePerSession: 6000,
    city: "Online",
    rating: 4.7,
    reviews: 25,
    category: "ancestral",
  },
  {
    id: "demo-pro-30",
    name: "Helena Sophia",
    title: "Especialista en Textos Apócrifos y Gnósticos",
    bio: "Estudiosa de los evangelios apócrifos, la Biblioteca de Nag Hammadi y la tradición gnóstica. Descubre los textos prohibidos que revelan enseñanzas ocultas del cristianismo primitivo.",
    specialties: ["Evangelios Apócrifos", "Nag Hammadi", "Gnosticismo", "Textos Prohibidos", "Cristianismo Primitivo"],
    pricePerSession: 5000,
    city: "Online",
    rating: 4.8,
    reviews: 19,
    category: "ancestral",
  },
  {
    id: "demo-pro-31",
    name: "Maestro Pythagoras Nova",
    title: "Numerólogo y Geometría Sagrada",
    bio: "Maestro en numerología pitagórica, cabalística y aplicada. Estudio del poder de los números, la geometría sagrada y su influencia en la vida cotidiana y el destino.",
    specialties: ["Numerología Pitagórica", "Numerología Cabalística", "Geometría Sagrada", "Número de Vida", "Gematría"],
    pricePerSession: 5000,
    city: "Barcelona",
    rating: 4.8,
    reviews: 42,
    category: "hermetismo",
  },
  {
    id: "demo-pro-32",
    name: "Hermes Trismegisto",
    title: "Maestro de Hermetismo y Alquimia",
    bio: "Guía en el estudio del Corpus Hermeticum, la Tabla Esmeralda y la alquimia espiritual. Transmisor de la tradición hermética para la transformación interior y la iluminación.",
    specialties: ["Hermetismo", "Alquimia", "Corpus Hermeticum", "Tabla Esmeralda", "Filosofía Oculta"],
    pricePerSession: 7500,
    city: "Online",
    rating: 5,
    reviews: 27,
    category: "hermetismo",
  },
  {
    id: "demo-pro-33",
    name: "Caminos del Alma",
    title: "Guía de Viajes Iniciáticos",
    bio: "Organizo peregrinaciones y viajes iniciáticos a Tierra Santa, Egipto, Grecia y Turquía. Rutas espirituales diseñadas para vivir una experiencia transformadora en lugares sagrados.",
    specialties: ["Peregrinaciones", "Tierra Santa", "Egipto Iniciático", "Grecia Antigua", "Rutas Espirituales"],
    pricePerSession: 0,
    city: "Varios destinos",
    rating: 4.9,
    reviews: 56,
    category: "viajes",
  },
  {
    id: "demo-pro-34",
    name: "Ruta Chamánica Global",
    title: "Organizadora de Viajes de Sanación",
    bio: "Viajes iniciáticos a Machu Picchu, el Tíbet, Sedona y la Amazonía. Ceremonias con chamanes locales, plantas medicinales y rituales ancestrales de poder.",
    specialties: ["Machu Picchu", "Tíbet", "Sedona", "Ceremonias Chamánicas", "Plantas Medicinales"],
    pricePerSession: 0,
    city: "Lima / Cusco / Online",
    rating: 4.7,
    reviews: 38,
    category: "viajes",
  },
  {
    id: "demo-pro-35",
    name: "Peregrino Interior",
    title: "Guía de Itinerarios Espirituales",
    bio: "Diseño experiencias de viaje espiritual personalizadas: Camino de Santiago, retiros en monasterios, viajes a los templos egipcios, Stonehenge, Glastonbury y centros energéticos del planeta.",
    specialties: ["Camino de Santiago", "Templos Egipcios", "Stonehenge", "Centros Energéticos", "Monasterios"],
    pricePerSession: 0,
    city: "Santiago de Compostela / Online",
    rating: 4.8,
    reviews: 44,
    category: "viajes",
  },
  {
    id: "demo-pro-36",
    name: "Iniciación Sagrada",
    title: "Guía de Templos y Pirámides",
    bio: "Viajes iniciáticos a las pirámides de Egipto, los templos de Grecia, las ruinas mayas y otros lugares de poder. Ceremonias de iniciación en templos antiguos.",
    specialties: ["Pirámides de Egipto", "Templos Griegos", "Ruinas Mayas", "Lugares de Poder", "Ceremonias de Iniciación"],
    pricePerSession: 0,
    city: "Egipto / Grecia / México",
    rating: 4.6,
    reviews: 33,
    category: "viajes",
  },
  {
    id: "demo-pro-37",
    name: "Artesano del Sonido",
    title: "Maestro de Cuencos Tibetanos y Gongs",
    bio: "Artesano y terapeuta especializado en cuencos tibetanos, gongs planetarios, campanas de viento y diapasones. Venta de instrumentos de sanación sonora y sesiones de baño de sonido.",
    specialties: ["Cuencos Tibetanos", "Gongs", "Campanas de Viento", "Bathos de Sonido", "Instrumentos de Sanación"],
    pricePerSession: 0,
    city: "Barcelona",
    rating: 4.9,
    reviews: 63,
    category: "materiales",
  },
  {
    id: "demo-pro-38",
    name: "Cristal del Alma",
    title: "Gemoterapeuta y Venta de Cristales",
    bio: "Tienda especializada en cristales, piedras semipreciosas, minerales y fósiles. Asesoramiento personalizado sobre la piedra adecuada para cada necesidad energética y emocional.",
    specialties: ["Cristales", "Piedras Semipreciosas", "Gemoterapia", "Minerales", "Joyería Energética"],
    pricePerSession: 0,
    city: "Madrid",
    rating: 4.8,
    reviews: 89,
    category: "materiales",
  },
  {
    id: "demo-pro-39",
    name: "Inciensos y Velas Sagradas",
    title: "Artesana de Inciensos Naturales y Velas Rituales",
    bio: "Elaboración artesanal de inciensos naturales, sahumerios, palo santo, velas rituales y aceites esenciales. Productos hechos a mano con ingredientes orgánicos y respetuosos con la tierra.",
    specialties: ["Inciensos Naturales", "Velas Rituales", "Sahumerios", "Palo Santo", "Aceites Esenciales"],
    pricePerSession: 0,
    city: "Valencia",
    rating: 4.7,
    reviews: 45,
    category: "materiales",
  },
  {
    id: "demo-pro-40",
    name: "Mandalas y Arte Sagrado",
    title: "Artista de Mandalas y Yantras",
    bio: "Creación de mandalas, yantras, ruedas de medicina y arte sagrado para meditación y decoración espiritual. También imparto talleres de dibujo de mandalas como práctica meditativa.",
    specialties: ["Mandalas", "Yantras", "Arte Sagrado", "Ruedas de Medicina", "Talleres de Mandalas"],
    pricePerSession: 0,
    city: "Online",
    rating: 4.6,
    reviews: 31,
    category: "materiales",
  },
  {
    id: "demo-pro-41",
    name: "Herbolaria Mágica",
    title: "Herboristería Esotérica y Botánica Espiritual",
    bio: "Venta de hierbas, plantas medicinales, resinas, aceites esenciales y mezclas herbales para rituales, sanación y espiritualidad. Conocimiento tradicional de la herbolaria europea y americana.",
    specialties: ["Hierbas Medicinales", "Resinas", "Aceites Esenciales", "Herbolaria Ritual", "Botánica Espiritual"],
    pricePerSession: 0,
    city: "Sevilla",
    rating: 4.8,
    reviews: 52,
    category: "materiales",
  },
  {
    id: "demo-pro-42",
    name: "Librería Esotérica Lux",
    title: "Librería Especializada en Espiritualidad y Ocultismo",
    bio: "Librería con más de 2000 títulos sobre espiritualidad, ocultismo, cábala, hermetismo, religiones comparadas, textos apócrifos, mitología y filosofía perenne. Pedidos internacionales.",
    specialties: ["Libros Espirituales", "Textos Ocultos", "Literatura Esotérica", "Grimorios", "Filosofía Perenne"],
    pricePerSession: 0,
    city: "Online",
    rating: 4.9,
    reviews: 127,
    category: "materiales",
  },
]

export const DEMO_COURSES: DemoCourse[] = [
  {
    id: "demo-course-1",
    title: "Yoga para Despertar la Conciencia",
    instructor: "Luna Martínez",
    description: "Curso completo de 8 semanas con sesiones de yoga kundalini, meditaciones guiadas y enseñanzas espirituales para elevar tu vibración.",
    price: 8900,
    lessons: 24,
    duration: "8 semanas",
    category: "yoga",
  },
  {
    id: "demo-course-2",
    title: "Reiki Nivel I, II y Maestría",
    instructor: "Maestro Rei Kenji",
    description: "Formación completa de Reiki Usui. Desde la iniciación hasta el nivel de maestría. Incluye manuales y certificados.",
    price: 29700,
    lessons: 12,
    duration: "3 meses",
    category: "reiki",
  },
  {
    id: "demo-course-3",
    title: "Autoconocimiento a través de las Constelaciones",
    instructor: "Aisha Nuru",
    description: "Curso teórico-práctico de constelaciones familiares para sanar tu árbol genealógico y liberar patrones heredados.",
    price: 14700,
    lessons: 10,
    duration: "6 semanas",
    category: "terapias",
  },
  {
    id: "demo-course-4",
    title: "Mindfulness y Meditación para la Vida Diaria",
    instructor: "Maya Shri",
    description: "Aprende a meditar y llevar el mindfulness a tu día a día. Reduce el estrés, mejora tu concentración y encuentra paz interior.",
    price: 5900,
    lessons: 16,
    duration: "8 semanas",
    category: "meditacion",
  },
  {
    id: "demo-course-5",
    title: "Despertar Espiritual: Guía Práctica",
    instructor: "Ángel Luz",
    description: "Un viaje de 30 días hacia tu despertar espiritual. Ejercicios, meditaciones y enseñanzas para expandir tu conciencia.",
    price: 7900,
    lessons: 30,
    duration: "30 días",
    category: "crecimiento",
  },
  {
    id: "demo-course-6",
    title: "Sanación con Cuencos Tibetanos",
    instructor: "Krishna Das",
    description: "Aprende el arte de la sanación con cuencos tibetanos. Técnicas de masaje sonoro, equilibrado de chakras y meditación con sonido.",
    price: 9900,
    lessons: 8,
    duration: "4 semanas",
    category: "terapias",
  },
  {
    id: "demo-course-7",
    title: "Yoga Nidra: El Sueño Consciente",
    instructor: "Sara Shanti",
    description: "Sumérgete en la práctica del yoga nidra, la meditación del sueño consciente. Relajación profunda y regeneración celular.",
    price: 4500,
    lessons: 12,
    duration: "4 semanas",
    category: "yoga",
  },
  {
    id: "demo-course-8",
    title: "Flores de Bach: Sanación Emocional",
    instructor: "Aisha Nuru",
    description: "Aprende a usar las 38 esencias florales de Bach para equilibrar tus emociones y sanar conflictos internos.",
    price: 6900,
    lessons: 10,
    duration: "5 semanas",
    category: "terapias",
  },
  {
    id: "demo-course-9",
    title: "Tai Chi para la Salud y la Longevidad",
    instructor: "Maestro Li Chen",
    description: "Aprende la forma de Tai Chi estilo Yang. Mejora tu equilibrio, vitalidad y conexión cuerpo-mente.",
    price: 7500,
    lessons: 16,
    duration: "8 semanas",
    category: "actividades",
  },
  {
    id: "demo-course-10",
    title: "Bio-danza: El Arte de Vivir",
    instructor: "Valeria Luna",
    description: "Sumérgete en la bio-danza y descubre cómo el movimiento consciente puede transformar tu vida.",
    price: 5900,
    lessons: 10,
    duration: "5 semanas",
    category: "actividades",
  },
  {
    id: "demo-course-11",
    title: "Acupuntura para el Dolor Crónico",
    instructor: "Dr. Javier Montes",
    description: "Curso teórico-práctico sobre puntos de acupuntura para tratar dolores crónicos de espalda, cervicales, rodillas y cabeza.",
    price: 9900,
    lessons: 12,
    duration: "6 semanas",
    category: "medicina",
  },
  {
    id: "demo-course-12",
    title: "Ayurveda: La Ciencia de la Vida",
    instructor: "Ananda Ayurveda",
    description: "Introducción completa al Ayurveda. Aprende tu constitución (dosha), alimentación, rutinas diarias y tratamientos de desintoxicación.",
    price: 7900,
    lessons: 16,
    duration: "8 semanas",
    category: "medicina",
  },
  {
    id: "demo-course-13",
    title: "Introducción al Estudio de la Torá",
    instructor: "Rabino David Cohen",
    description: "Curso completo de iniciación al estudio de la Torá. Desde el Génesis hasta el Deuteronomio, con enfoque en el significado espiritual y la tradición rabínica.",
    price: 8900,
    lessons: 20,
    duration: "10 semanas",
    category: "tradiciones",
  },
  {
    id: "demo-course-14",
    title: "Los Evangelios: Historia, Contexto y Espiritualidad",
    instructor: "Dr. Mateo Ávila",
    description: "Estudio profundo de los cuatro evangelios canónicos. Contexto histórico, análisis textual y enseñanza espiritual para la vida contemporánea.",
    price: 7900,
    lessons: 16,
    duration: "8 semanas",
    category: "tradiciones",
  },
  {
    id: "demo-course-15",
    title: "El Libro de los Muertos Egipcio: Guía del Más Allá",
    instructor: "Dr. Anubis Amón",
    description: "Traducción y estudio de los textos funerarios egipcios. Los hechizos, las fórmulas y el viaje del alma en el más allá según la tradición del Kemet.",
    price: 9900,
    lessons: 14,
    duration: "7 semanas",
    category: "ancestral",
  },
  {
    id: "demo-course-16",
    title: "Textos Sumerios: El Origen de la Civilización",
    instructor: "Ziauddin Enki",
    description: "Lectura y análisis de las tablillas cuneiformes sumerias. El Enuma Elish, Gilgamesh, la creación del hombre y los misterios de los Anunnaki.",
    price: 9900,
    lessons: 18,
    duration: "9 semanas",
    category: "ancestral",
  },
  {
    id: "demo-course-17",
    title: "Numerología Sagrada: El Lenguaje de los Números",
    instructor: "Maestro Pythagoras Nova",
    description: "Aprende a calcular e interpretar los números de tu vida: número de nacimiento, destino, alma y personalidad. La numerología como herramienta de autoconocimiento.",
    price: 6900,
    lessons: 12,
    duration: "6 semanas",
    category: "hermetismo",
  },
  {
    id: "demo-course-18",
    title: "Introducción a la Cábala Práctica",
    instructor: "David Ben-Shalom",
    description: "Fundamentos de la Cábala: el Árbol de la Vida, las 10 sefirot, los 22 senderos y la meditación cabalística. Un curso para aplicar la sabiduría mística en tu vida.",
    price: 9900,
    lessons: 16,
    duration: "8 semanas",
    category: "hermetismo",
  },
]

export const DEMO_MEDITATIONS: DemoMeditation[] = [
  {
    id: "demo-med-1",
    title: "Meditación Guiada para Abrir el Corazón",
    instructor: "Maya Shri",
    duration: "15 min",
    description: "Una meditación suave para conectar con la energía del corazón y cultivar la compasión.",
    category: "meditacion",
  },
  {
    id: "demo-med-2",
    title: "Respiración Kundalini para Activar la Energía",
    instructor: "Luna Martínez",
    duration: "21 min",
    description: "Técnica de respiración kundalini para despertar la energía dormida en la base de la columna.",
    category: "yoga",
  },
  {
    id: "demo-med-3",
    title: "Meditación del Atardecer",
    instructor: "Sara Shanti",
    duration: "20 min",
    description: "Meditación guiada al atardecer para soltar el día y conectar con la gratitud.",
    category: "meditacion",
  },
  {
    id: "demo-med-4",
    title: "Mantra OM: Vibración Primordial",
    instructor: "Krishna Das",
    duration: "30 min",
    description: "Cántico del mantra OM con cuencos tibetanos para alinear tus chakras y elevar tu vibración.",
    category: "terapias",
  },
  {
    id: "demo-med-5",
    title: "Meditación para la Sanación Interior",
    instructor: "Maestro Rei Kenji",
    duration: "25 min",
    description: "Meditación guiada con símbolos de Reiki para sanar heridas emocionales y equilibrar la energía.",
    category: "reiki",
  },
  {
    id: "demo-med-6",
    title: "Yoga Nidra para Dormir Profundamente",
    instructor: "Sara Shanti",
    duration: "35 min",
    description: "Relajación guiada de yoga nidra para inducir un sueño profundo y reparador.",
    category: "yoga",
  },
  {
    id: "demo-med-7",
    title: "Meditación de los 7 Chakras",
    instructor: "Tara Devi",
    duration: "40 min",
    description: "Recorrido meditativo por los siete chakras principales con visualizaciones y mantras.",
    category: "meditacion",
  },
  {
    id: "demo-med-8",
    title: "Respiración Consciente para la Ansiedad",
    instructor: "Maya Shri",
    duration: "10 min",
    description: "Ejercicios de respiración consciente para calmar la ansiedad y volver al presente.",
    category: "meditacion",
  },
  {
    id: "demo-med-9",
    title: "Meditación de Conexión con la Tierra",
    instructor: "Naturaleza Viva Retiros",
    duration: "20 min",
    description: "Meditación guiada para enraizarte y conectar con la energía sanadora de la tierra.",
    category: "retiros",
  },
  {
    id: "demo-med-10",
    title: "Auto-Reiki: Sanación con las Manos",
    instructor: "Maestro Rei Kenji",
    duration: "15 min",
    description: "Práctica guiada de auto-reiki para armonizar tu energía en cualquier momento del día.",
    category: "reiki",
  },
  {
    id: "demo-med-11",
    title: "Chi Kung de los 5 Elementos",
    instructor: "Maestro Li Chen",
    duration: "20 min",
    description: "Secuencia de Chi Kung para armonizar los cinco elementos y equilibrar tu energía vital.",
    category: "actividades",
  },
  {
    id: "demo-med-12",
    title: "Meditación en Movimiento: Danza Libre",
    instructor: "Mónica Paz",
    duration: "25 min",
    description: "Una meditación guiada a través del movimiento libre y la danza consciente.",
    category: "actividades",
  },
]

export const DEMO_EVENTS: DemoEvent[] = [
  {
    id: "demo-ev-1",
    title: "Retiro de Silencio y Meditación",
    organizer: "Maya Shri",
    date: "15-20 Junio 2026",
    location: "Ibiza",
    price: 45000,
    description: "5 días de silencio, meditación y conexión profunda en un entorno natural privilegiado.",
    category: "retiros",
    type: "retiro",
  },
  {
    id: "demo-ev-2",
    title: "Taller de Constelaciones Familiares",
    organizer: "Aisha Nuru",
    date: "3-4 Mayo 2026",
    location: "Barcelona",
    price: 12000,
    description: "Taller intensivo de constelaciones familiares para sanar tu sistema familiar.",
    category: "terapias",
    type: "taller",
  },
  {
    id: "demo-ev-3",
    title: "Ceremonia de Cacao y Yoga bajo la Luna",
    organizer: "Luna Martínez",
    date: "28 Abril 2026",
    location: "Barcelona",
    price: 2500,
    description: "Ceremonia de cacao sagrado seguida de yoga y meditación bajo la luz de la luna llena.",
    category: "yoga",
    type: "ceremonia",
  },
  {
    id: "demo-ev-4",
    title: "Formación de Reiki Usui Nivel I",
    organizer: "Maestro Rei Kenji",
    date: "10-12 Mayo 2026",
    location: "Valencia",
    price: 15000,
    description: "Iniciación al Reiki Usui Nivel I. Incluye manual, certificado y prácticas supervisadas.",
    category: "reiki",
    type: "formacion",
  },
  {
    id: "demo-ev-5",
    title: "Retiro de Yoga y Ayurveda",
    organizer: "Naturaleza Viva Retiros",
    date: "1-8 Julio 2026",
    location: "Sierra Nevada",
    price: 65000,
    description: "Una semana de yoga, meditación, alimentación ayurvédica y baños de bosque.",
    category: "retiros",
    type: "retiro",
  },
  {
    id: "demo-ev-6",
    title: "Taller de Respiración Consciente",
    organizer: "Sara Shanti",
    date: "20 Mayo 2026",
    location: "Sevilla",
    price: 3500,
    description: "Aprende técnicas de respiración consciente para transformar tu energía y calmar tu mente.",
    category: "crecimiento",
    type: "taller",
  },
  {
    id: "demo-ev-7",
    title: "Círculo de Tai Chi al Amanecer",
    organizer: "Maestro Li Chen",
    date: "Cada sábado",
    location: "Parc de la Ciutadella, Barcelona",
    price: 1500,
    description: "Práctica grupal de Tai Chi al aire libre. Abierto a todos los niveles. Trae ropa cómoda.",
    category: "actividades",
    type: "taller",
  },
  {
    id: "demo-ev-8",
    title: "Encuentro de Bio-danza y Danza Circular",
    organizer: "Valeria Luna",
    date: "Último viernes de cada mes",
    location: "Centro Holístico Armonía, Madrid",
    price: 2000,
    description: "Encuentro mensual de bio-danza y danza circular para conectar con la comunidad y la alegría.",
    category: "actividades",
    type: "taller",
  },
  {
    id: "demo-ev-9",
    title: "Ecstatic Dance: Viaje de Movimiento y Música",
    organizer: "Mónica Paz",
    date: "15 Junio 2026",
    location: "Espacio Sagrado, Ibiza",
    price: 2500,
    description: "2 horas de danza libre y consciente con música en vivo. Una experiencia de conexión profunda.",
    category: "actividades",
    type: "ceremonia",
  },
  {
    id: "demo-ev-10",
    title: "Feria Holística de Primavera",
    organizer: "Asociación Holística Madrid",
    date: "24-26 Mayo 2026",
    location: "Pabellón de Cristal, Madrid",
    city: "Madrid",
    price: 800,
    description: "La mayor feria holística de Madrid con más de 80 expositores. Terapias, productos naturales, conferencias, talleres y demostraciones en vivo.",
    category: "zona",
    type: "feria",
  },
  {
    id: "demo-ev-11",
    title: "Mercado Esotérico de la Luna Nueva",
    organizer: "Colectivo Esotérico Barcelona",
    date: "7 Junio 2026",
    location: "Plaza del Sol, Barcelona",
    city: "Barcelona",
    price: 0,
    description: "Mercado al aire libre con puestos de tarot, cristales, inciensos, velas, libros esotéricos y lecturas de cartas. Entrada gratuita.",
    category: "zona",
    type: "mercado",
  },
  {
    id: "demo-ev-12",
    title: "Feria de la Brujería y el Ocultismo",
    organizer: "Círculo de la Sombra",
    date: "13-15 Junio 2026",
    location: "Ateneo Cultural, Valencia",
    city: "Valencia",
    price: 1200,
    description: "Tres días dedicados a la brujería tradicional, el ocultismo, grimorios antiguos, demonología y la figura de la Diosa Oscura. Conferencias, talleres y rituales.",
    category: "zona",
    type: "feria",
  },
  {
    id: "demo-ev-13",
    title: "Feria de Cristales, Piedras y Minerales",
    organizer: "Gemoterapia España",
    date: "17-18 Mayo 2026",
    location: "Hotel Auditorium, Madrid",
    city: "Madrid",
    price: 500,
    description: "Exposición y venta de cristales, piedras semipreciosas, minerales, fósiles y joyería energética. Expertos en gemoterapia resolverán tus dudas.",
    category: "zona",
    type: "feria",
  },
  {
    id: "demo-ev-14",
    title: "Círculo de Mujeres: Luna Llena en Sagitario",
    organizer: "Hermandad de la Luna",
    date: "30 Mayo 2026",
    location: "Centro Alma Femenina, Sevilla",
    city: "Sevilla",
    price: 1500,
    description: "Círculo sagrado de mujeres para conectar con la energía de la luna llena. Meditación, tambor, cánticos, intención compartida y hermandad.",
    category: "zona",
    type: "circulo",
  },
  {
    id: "demo-ev-15",
    title: "Mercado de Terapias Alternativas y Productos Naturales",
    organizer: "Vida Sana Eventos",
    date: "8 Junio 2026",
    location: "Parque del Retiro, Madrid",
    city: "Madrid",
    price: 0,
    description: "Mercado mensual con terapeutas, vendedores de productos ecológicos, alimentación consciente, cosmética natural y demostraciones de terapias.",
    category: "zona",
    type: "mercado",
  },
  {
    id: "demo-ev-16",
    title: "Charla: Los Evangelios Apócrifos y el Jesús Gnóstico",
    organizer: "Helena Sophia",
    date: "22 Mayo 2026",
    location: "Online / Zoom",
    city: "Online",
    price: 1000,
    description: "Conferencia online sobre los evangelios apócrifos de Nag Hammadi, el Jesús gnóstico y las enseñanzas secretas del cristianismo primitivo.",
    category: "zona",
    type: "charla",
  },
  {
    id: "demo-ev-17",
    title: "Feria de la Medicina Natural y la Herbolaria",
    organizer: "Centro de Salud Holística",
    date: "21-22 Junio 2026",
    location: "Feria de Muestras, Valladolid",
    city: "Valladolid",
    price: 600,
    description: "Feria dedicada a la medicina natural, fitoterapia, herboristería, aceites esenciales y alimentación viva. Talleres prácticos y consultas gratuitas.",
    category: "zona",
    type: "feria",
  },
  {
    id: "demo-ev-18",
    title: "Encuentro de Cánticos Devocionales y Mantras",
    organizer: "Krishna Das",
    date: "Primer sábado de cada mes",
    location: "Centro de Yoga Shanti, Barcelona",
    city: "Barcelona",
    price: 1000,
    description: "Encuentro mensual de kirtan, cánticos devocionales y mantras. Abierto a todos. Trae tu instrumento si quieres o solo ven a cantar.",
    category: "zona",
    type: "encuentro",
  },
]

export const DEMO_PODCASTS: DemoPodcast[] = [
  {
    id: "demo-pod-1",
    title: "El Despertar de la Conciencia",
    host: "Luna Martínez",
    duration: "45 min",
    description: "Conversaciones semanales sobre espiritualidad, yoga y crecimiento personal. Invitados especiales y enseñanzas prácticas.",
    episodes: 128,
    category: "yoga",
    isTop: true,
  },
  {
    id: "demo-pod-2",
    title: "Reiki y Sanación Energética",
    host: "Maestro Rei Kenji",
    duration: "30 min",
    description: "Todo sobre Reiki, sanación energética y cómo elevar tu vibración a través de la energía universal.",
    episodes: 64,
    category: "reiki",
    isTop: true,
  },
  {
    id: "demo-pod-3",
    title: "Mindfulness para tu Día a Día",
    host: "Maya Shri",
    duration: "20 min",
    description: "Píldoras diarias de mindfulness y meditación para integrar la atención plena en tu rutina.",
    episodes: 256,
    category: "meditacion",
    isTop: true,
  },
  {
    id: "demo-pod-4",
    title: "Terapias Holísticas: El Poder de Sanar",
    host: "Aisha Nuru",
    duration: "50 min",
    description: "Exploramos constelaciones, flores de Bach, biomagnetismo y todas las terapias alternativas.",
    episodes: 89,
    category: "terapias",
    isTop: true,
  },
  {
    id: "demo-pod-5",
    title: "Camino Espiritual: Conversaciones con el Alma",
    host: "Ángel Luz",
    duration: "40 min",
    description: "Entrevistas profundas con buscadores espirituales, maestros y facilitadores de despertar.",
    episodes: 73,
    category: "crecimiento",
    isTop: true,
  },
  {
    id: "demo-pod-6",
    title: "Cuerpo en Movimiento: Tai Chi y Chi Kung",
    host: "Maestro Li Chen",
    duration: "25 min",
    description: "Prácticas guiadas de Tai Chi, Chi Kung y meditación en movimiento para tu salud física y espiritual.",
    episodes: 52,
    category: "actividades",
    isTop: true,
  },
  {
    id: "demo-pod-7",
    title: "Danza y Espiritualidad",
    host: "Valeria Luna",
    duration: "35 min",
    description: "La danza como camino de conexión espiritual. Bio-danza, danza circular y movimiento consciente.",
    episodes: 41,
    category: "actividades",
    isTop: false,
  },
  {
    id: "demo-pod-8",
    title: "Retiros que Transforman",
    host: "Naturaleza Viva Retiros",
    duration: "55 min",
    description: "Historias y experiencias de retiros espirituales alrededor del mundo. Inspiración para tu próximo viaje interior.",
    episodes: 37,
    category: "retiros",
    isTop: false,
  },
  {
    id: "demo-pod-9",
    title: "Música Devocional y Mantras",
    host: "Krishna Das",
    duration: "60 min",
    description: "Programa semanal de música devocional, mantras, cuencos tibetanos y sound healing.",
    episodes: 95,
    category: "terapias",
    isTop: false,
  },
  {
    id: "demo-pod-10",
    title: "Yoga Nidra y Relajación Profunda",
    host: "Sara Shanti",
    duration: "30 min",
    description: "Sesiones guiadas de yoga nidra, relajación profunda y meditación del sueño consciente.",
    episodes: 118,
    category: "yoga",
    isTop: false,
  },
  {
    id: "demo-pod-11",
    title: "La Senda de la Sombra",
    host: "Astaroth Blackwood",
    duration: "50 min",
    description: "Exploración profunda del ocultismo, la magia ceremonial y la tradición esotérica occidental. Grimorios, sellos, invocaciones y el camino de la mano izquierda.",
    episodes: 67,
    category: "ocultismo",
    isTop: true,
  },
  {
    id: "demo-pod-12",
    title: "Rituales Prohibidos",
    host: "Lilith Nocturna",
    duration: "45 min",
    description: "Historia del satanismo, magia negra y rituales de poder. Desde la tradición laveyana hasta el satanismo teísta y las corrientes ocultas contemporáneas.",
    episodes: 43,
    category: "ocultismo",
    isTop: true,
  },
  {
    id: "demo-pod-13",
    title: "El Libro de la Sombra",
    host: "Morgana Le Fay",
    duration: "40 min",
    description: "Wicca, brujería tradicional y neopaganismo. Prácticas de la Rueda del Año, herbología mágica, rituales de la luna y el arte de la hechicería natural.",
    episodes: 89,
    category: "ocultismo",
    isTop: true,
  },
  {
    id: "demo-pod-14",
    title: "Demonios y Ángeles Caídos",
    host: "Dr. Carmín Sombra",
    duration: "55 min",
    description: "Demonología, angelología oscura y la caída de Lucifer. Estudio de grimorios como La Llave de Salomón, el Ars Goetia y la jerarquía demoníaca.",
    episodes: 52,
    category: "ocultismo",
    isTop: true,
  },
  {
    id: "demo-pod-15",
    title: "La Llave de Salomón",
    host: "Enoc Mathers",
    duration: "60 min",
    description: "Magia ritual, grimorios y tradiciones ocultas. Análisis detallado de la Clavícula de Salomón, la Cábala práctica y la magia enoquiana.",
    episodes: 38,
    category: "ocultismo",
    isTop: false,
  },
  {
    id: "demo-pod-16",
    title: "Cultos y Sectas: El Lado Oscuro de la Fe",
    host: "Iván de la Cruz",
    duration: "70 min",
    description: "Análisis de cultos ocultistas, sectas satánicas y grupos esotéricos radicales a lo largo de la historia. Manipulación, poder y creencias extremas.",
    episodes: 46,
    category: "ocultismo",
    isTop: false,
  },
  {
    id: "demo-pod-17",
    title: "El Otro Lado",
    host: "Médium Azrael",
    duration: "35 min",
    description: "Mediumnidad, espiritismo, contacto con entidades y comunicación con los muertos. Sesiones espiritistas, ouija y fenómenos paranormales.",
    episodes: 74,
    category: "ocultismo",
    isTop: false,
  },
  {
    id: "demo-pod-18",
    title: "Lucifer: Luz y Sombra",
    host: "Dr. Ángel Luzbel",
    duration: "50 min",
    description: "La figura de Lucifer en el ocultismo, la teología y la cultura. Desde el portador de luz hasta el príncipe de las tinieblas. Una mirada sin prejuicios.",
    episodes: 31,
    category: "ocultismo",
    isTop: false,
  },
]

export const DEMO_ACTIVITIES: DemoActivity[] = [
  {
    id: "demo-act-1",
    name: "Grupo de Yoga al Amanecer",
    instructor: "Gabriel Sol",
    type: "Yoga Grupal",
    description: "Clases de yoga al aire libre en la playa al amanecer. Todos los niveles bienvenidos.",
    schedule: "Lun, Mié, Vie 6:30-7:30",
    location: "Playa de la Malvarrosa, Valencia",
    price: 1200,
    category: "actividades",
  },
  {
    id: "demo-act-2",
    name: "Tai Chi en el Parque",
    instructor: "Maestro Li Chen",
    type: "Tai Chi",
    description: "Práctica grupal de Tai Chi estilo Yang. Mejora tu equilibrio, flexibilidad y paz interior.",
    schedule: "Sáb 8:00-9:30",
    location: "Parc de la Ciutadella, Barcelona",
    price: 1000,
    category: "actividades",
  },
  {
    id: "demo-act-3",
    name: "Círculo de Bio-danza",
    instructor: "Valeria Luna",
    type: "Bio-danza",
    description: "Encuentro semanal de bio-danza para conectar con tu cuerpo, tus emociones y la comunidad.",
    schedule: "Jue 19:00-21:00",
    location: "Centro Holístico Armonía, Madrid",
    price: 1500,
    category: "actividades",
  },
  {
    id: "demo-act-4",
    name: "Ecstatic Dance Ibiza",
    instructor: "Mónica Paz",
    type: "Danza Consciente",
    description: "2 horas de danza libre con DJ en vivo. Un viaje de movimiento, música y conexión espiritual.",
    schedule: "Sáb 18:00-20:00",
    location: "Espacio Sagrado, Ibiza",
    price: 1800,
    category: "actividades",
  },
  {
    id: "demo-act-5",
    name: "Chi Kung Matutino",
    instructor: "Maestro Li Chen",
    type: "Chi Kung",
    description: "Práctica diaria de Chi Kung para activar la energía vital y empezar el día con vitalidad.",
    schedule: "Lun a Vie 7:00-7:45",
    location: "Online / Zoom",
    price: 800,
    category: "actividades",
  },
  {
    id: "demo-act-6",
    name: "Danza Circular de la Luna",
    instructor: "Valeria Luna",
    type: "Danza Circular",
    description: "Círculo de danza circular en conexión con los ciclos lunares. Mujeres y hombres bienvenidos.",
    schedule: "Una vez al mes (luna llena)",
    location: "Centro de la Tierra, Madrid",
    price: 1000,
    category: "actividades",
  },
  {
    id: "demo-act-7",
    name: "Yoga para Embarazadas",
    instructor: "Sara Shanti",
    type: "Yoga Terapéutico",
    description: "Yoga suave y consciente para embarazadas. Preparación física y emocional para el parto.",
    schedule: "Mar y Jue 17:00-18:15",
    location: "Estudio Shanti, Sevilla",
    price: 1400,
    category: "actividades",
  },
  {
    id: "demo-act-8",
    name: "Yoga Familiar en la Naturaleza",
    instructor: "Gabriel Sol",
    type: "Yoga Grupal",
    description: "Yoga para toda la familia. Niños y adultos practican juntos en plena naturaleza.",
    schedule: "Dom 10:00-11:15",
    location: "Parque Natural de la Albufera, Valencia",
    price: 2000,
    category: "actividades",
  },
]

export const CATEGORIES = [
  {
    id: "yoga",
    name: "Yoga",
    icon: "🧘",
    description: "Profesores, cursos y retiros de yoga para despertar tu energía",
    longDescription: "Aquí encontrarás profesores de todos los estilos: Hatha, Vinyasa, Kundalini, Ashtanga, Iyengar, Yoga Nidra y más. También cursos de formación, retiros de yoga y sesiones individuales. El yoga es una disciplina que integra posturas físicas (asanas), respiración (pranayama), meditación y filosofía para equilibrar cuerpo, mente y espíritu.",
    keywords: ["yoga", "kundalini", "hatha", "ashtanga", "vinyasa", "iyengar", "nidra", "pranayama"],
    color: "from-amber-500/20 to-orange-500/5",
    borderColor: "border-amber-500/30",
    textColor: "text-amber-300",
    bgColor: "bg-amber-500/10",
    gradient: "from-amber-900/40 via-purple-900/20 to-transparent",
  },
  {
    id: "reiki",
    name: "Reiki",
    icon: "✨",
    description: "Sesiones, cursos y formaciones de Reiki",
    longDescription: "El Reiki es una técnica de sanación energética de origen japonés que canaliza la energía universal a través de las manos. Aquí encontrarás maestros de Reiki Usui, Karuna Reiki y otras líneas, que ofrecen sesiones de sanación, iniciaciones y formaciones completas desde nivel I hasta maestría.",
    keywords: ["reiki", "usui", "karuna", "sanación"],
    color: "from-violet-500/20 to-purple-500/5",
    borderColor: "border-violet-500/30",
    textColor: "text-violet-300",
    bgColor: "bg-violet-500/10",
    gradient: "from-violet-900/40 via-purple-900/20 to-transparent",
  },
  {
    id: "terapias",
    name: "Terapias Alternativas",
    icon: "🌿",
    description: "Constelaciones, flores de Bach, biomagnetismo, sonido",
    longDescription: "Un espacio dedicado a las terapias complementarias y holísticas: constelaciones familiares, flores de Bach, biomagnetismo, cuencos tibetanos, masaje terapéutico, sanación con sonido y todas las herramientas de sanación alternativa que trabajan con la energía, las emociones y el alma.",
    keywords: ["flores", "bach", "constelaciones", "biomagnetismo", "cuencos", "sonido", "masaje", "acupuntura", "terapia", "sanación"],
    color: "from-emerald-500/20 to-teal-500/5",
    borderColor: "border-emerald-500/30",
    textColor: "text-emerald-300",
    bgColor: "bg-emerald-500/10",
    gradient: "from-emerald-900/40 via-purple-900/20 to-transparent",
  },
  {
    id: "meditacion",
    name: "Meditación & Mindfulness",
    icon: "🪷",
    description: "Meditaciones guiadas, mindfulness y atención plena",
    longDescription: "Encuentra guías de meditación, instructores de mindfulness y maestros de atención plena. Desde meditación Vipassana y trascendental hasta meditaciones guiadas para reducir el estrés, la ansiedad y cultivar la paz interior. También incluye retiros de silencio, cursos de mindfulness y prácticas diarias.",
    keywords: ["meditación", "meditacion", "mindfulness", "atención plena", "vipassana", "trascendental"],
    color: "from-sky-500/20 to-blue-500/5",
    borderColor: "border-sky-500/30",
    textColor: "text-sky-300",
    bgColor: "bg-sky-500/10",
    gradient: "from-sky-900/40 via-indigo-900/20 to-transparent",
  },
  {
    id: "crecimiento",
    name: "Crecimiento Personal",
    icon: "🌱",
    description: "Talleres, formaciones y desarrollo espiritual",
    longDescription: "Talleres, formaciones y sesiones para tu desarrollo personal y despertar espiritual. Aquí encontrarás coaches espirituales, facilitadores de transformación, guías de conciencia, mediumnidad, intuición y videncia. Un espacio para explorar quién eres realmente y expandir tu potencial ilimitado.",
    keywords: ["crecimiento", "desarrollo", "taller", "holístico", "holistico", "espiritual", "conciencia", "transformación", "coaching", "cábala", "cabala", "medium", "mediumnidad", "mística", "mistica", "zohar", "árbol de la vida", "arbol de la vida", "intuición", "intuicion", "vidente", "videncia"],
    color: "from-rose-500/20 to-pink-500/5",
    borderColor: "border-rose-500/30",
    textColor: "text-rose-300",
    bgColor: "bg-rose-500/10",
    gradient: "from-rose-900/40 via-purple-900/20 to-transparent",
  },
  {
    id: "retiros",
    name: "Eventos & Retiros",
    icon: "🔥",
    description: "Retiros espirituales, ceremonias y eventos",
    longDescription: "Retiros espirituales, ceremonias, eventos presenciales y formaciones intensivas. Desde retiros de silencio en la naturaleza hasta ceremonias de luna llena, pasando por formaciones presenciales de fin de semana. Desconecta de la rutina y conéctate con tu esencia en entornos sagrados.",
    keywords: ["retiro", "evento", "ceremonia", "taller presencial", "naturaleza"],
    color: "from-orange-500/20 to-yellow-500/5",
    borderColor: "border-orange-500/30",
    textColor: "text-orange-300",
    bgColor: "bg-orange-500/10",
    gradient: "from-orange-900/40 via-amber-900/20 to-transparent",
  },
  {
    id: "actividades",
    name: "Actividades Físicas Espirituales",
    icon: "💃",
    description: "Tai Chi, Bio-danza, Chi Kung, danza consciente y movimiento espiritual",
    longDescription: "El movimiento como camino espiritual. Grupos de yoga al aire libre, Tai Chi, Chi Kung, Bio-danza, danza consciente, ecstatic dance y otras prácticas que integran el cuerpo en la experiencia espiritual. Conecta con tu cuerpo, libera energía y eleva tu vibración a través del movimiento consciente.",
    keywords: ["tai chi", "chi kung", "bio-danza", "danza", "movimiento", "ecstatic", "yoga grupal"],
    color: "from-teal-500/20 to-cyan-500/5",
    borderColor: "border-teal-500/30",
    textColor: "text-teal-300",
    bgColor: "bg-teal-500/10",
    gradient: "from-teal-900/40 via-emerald-900/20 to-transparent",
  },
  {
    id: "podcasts",
    name: "Podcasts Espirituales",
    icon: "🎙️",
    description: "Podcasts recomendados sobre espiritualidad, yoga, meditación y crecimiento",
    longDescription: "La mejor selección de podcasts sobre espiritualidad, yoga, meditación, crecimiento personal, terapias alternativas y desarrollo de la conciencia. Episodios semanales con expertos, enseñanzas prácticas y conversaciones profundas para nutrir tu alma en cualquier momento y lugar.",
    keywords: [],
    color: "from-pink-500/20 to-fuchsia-500/5",
    borderColor: "border-pink-500/30",
    textColor: "text-pink-300",
    bgColor: "bg-pink-500/10",
    gradient: "from-pink-900/40 via-fuchsia-900/20 to-transparent",
  },
  {
    id: "medicina",
    name: "Medicina Alternativa",
    icon: "🏥",
    description: "Acupuntura, osteopatía, naturopatía, Ayurveda, medicina china y homeopatía",
    longDescription: "Profesionales de la salud natural y la medicina complementaria: acupuntura, osteopatía, naturopatía, Ayurveda, medicina tradicional china, homeopatía, fitoterapia y herbolaria. Una visión integral de la salud que combina el conocimiento ancestral con la ciencia moderna para tratar cuerpo, mente y espíritu.",
    keywords: ["acupuntura", "osteopatía", "osteopatia", "naturopatía", "naturopatia", "ayurveda", "homeopatía", "homeopatia", "medicina china", "fitoterapia", "herbolaria"],
    color: "from-red-500/20 to-rose-500/5",
    borderColor: "border-red-500/30",
    textColor: "text-red-300",
    bgColor: "bg-red-500/10",
    gradient: "from-red-900/40 via-rose-900/20 to-transparent",
  },
  {
    id: "ocultismo",
    name: "Ocultismo",
    icon: "🔮",
    description: "Podcasts sobre ocultismo, satanismo, demonología, brujería, grimorios y el lado oscuro de la espiritualidad",
    longDescription: "Un espacio dedicado a los podcasts que exploran el lado oscuro y oculto de la espiritualidad: ocultismo, satanismo, demonología, brujería tradicional y moderna (Wicca, neopaganismo), grimorios como La Llave de Salomón, cultos y sectas, espiritismo, ángeles caídos y la figura de Lucifer. Contenido para mentes curiosas sin prejuicios.",
    keywords: ["ocultismo", "satanismo", "demonología", "demonologia", "brujería", "brujeria", "grimorio", "magia negra", "wolfcraft", "wicca", "neopaganismo", "ángeles caídos", "angeles caidos", "llave de salomón", "salomon", "cultos", "sectas", "espiritismo", "lucifer"],
    color: "from-gray-800/40 to-zinc-900/20",
    borderColor: "border-gray-700/30",
    textColor: "text-gray-300",
    bgColor: "bg-gray-800/20",
    gradient: "from-gray-900/60 via-zinc-900/40 to-transparent",
  },
  {
    id: "tarot",
    name: "Tarot y Adivinación",
    icon: "🃏",
    description: "Tarot, astrología, oráculos, runas y todas las artes adivinatorias",
    longDescription: "Lectura de tarot terapéutico, cartas astrales, oráculos, runas nórdicas, quiromancia, lectura de velas y todas las artes de adivinación y videncia. Profesionales que te ayudarán a encontrar claridad, propósito y dirección a través de las herramientas de percepción del futuro y autoconocimiento profundo.",
    keywords: ["tarot", "astrología", "astrologia", "adivinación", "adivinacion", "oráculo", "oraculo", "cartas", "runas", "quiromancia", "videncia", "lectura de velas", "carta natal", "sinastría", "numerología"],
    color: "from-fuchsia-500/20 to-pink-500/5",
    borderColor: "border-fuchsia-500/30",
    textColor: "text-fuchsia-300",
    bgColor: "bg-fuchsia-500/10",
    gradient: "from-fuchsia-900/40 via-pink-900/20 to-transparent",
  },
  {
    id: "tradiciones",
    name: "Tradiciones Sagradas",
    icon: "📜",
    description: "Estudio de la Torá, Biblia, Evangelios, textos sagrados y exégesis espiritual",
    longDescription: "Profesores y guías especializados en el estudio de las sagradas escrituras: Torá, Talmud, Biblia, Evangelios, cartas paulinas, Apocalipsis y literatura rabínica. Exégesis bíblica, teología, lectio divina y mística cristiana. Un acercamiento erudito y espiritual a los textos fundacionales de las grandes tradiciones religiosas.",
    keywords: ["torá", "tora", "biblia", "evangelio", "evangelios", "exégesis", "exegesis", "rabino", "rabínico", "rabinico", "talmud", "sagrada escritura", "sagradas escrituras", "teología", "teologia", "pentateuco", "profetas"],
    color: "from-blue-800/40 to-indigo-900/20",
    borderColor: "border-blue-700/30",
    textColor: "text-blue-300",
    bgColor: "bg-blue-800/20",
    gradient: "from-blue-900/50 via-indigo-900/30 to-transparent",
  },
  {
    id: "ancestral",
    name: "Sabiduría Ancestral",
    icon: "🏛️",
    description: "Textos sumerios, egipcios, apócrifos, gnósticos y tradiciones de civilizaciones antiguas",
    longDescription: "El conocimiento oculto de las civilizaciones antiguas: tablillas sumerias y acadias (Enuma Elish, Gilgamesh, los Anunnaki), textos egipcios (Libro de los Muertos, papiros, misterios de las pirámides), evangelios apócrifos y la Biblioteca de Nag Hammadi, tradiciones gnósticas y herméticas. Los saberes prohibidos que la historia oficial no cuenta.",
    keywords: ["sumerio", "egipcio", "apócrifo", "apocrifo", "gnóstico", "gnostico", "hermético", "hermetico", "corpus hermeticum", "egipto", "sumeria", "tabletas", "cuneiforme", "misterios antiguos", "libro de los muertos", "papiros", "thoth"],
    color: "from-amber-800/40 to-yellow-900/20",
    borderColor: "border-amber-700/30",
    textColor: "text-amber-300",
    bgColor: "bg-amber-800/20",
    gradient: "from-amber-900/50 via-yellow-900/30 to-transparent",
  },
  {
    id: "hermetismo",
    name: "Hermetismo y Numerología",
    icon: "🔢",
    description: "Cábala, numerología aplicada, gematría, hermetismo, alquimia y ciencias ocultas",
    longDescription: "Las ciencias ocultas y la sabiduría hermética: Cábala (Árbol de la Vida, Zohar, sefirot), numerología pitagórica y cabalística aplicada, gematría, hermetismo (Corpus Hermeticum, Tabla Esmeralda), alquimia espiritual y filosofía oculta. Maestros que te guiarán en el estudio de las tradiciones esotéricas que revelan los misterios del universo.",
    keywords: ["cábala", "cabala", "numerología", "numerologia", "gematría", "gematria", "hermetismo", "alquimia", "árbol de la vida", "arbol de la vida", "sefirot", "temurá", "notaricón", "notaricon", "zohar", "pitagórica", "pitagorica"],
    color: "from-purple-800/40 to-fuchsia-900/20",
    borderColor: "border-purple-700/30",
    textColor: "text-purple-300",
    bgColor: "bg-purple-800/20",
    gradient: "from-purple-900/50 via-fuchsia-900/30 to-transparent",
  },
  {
    id: "viajes",
    name: "Viajes Iniciáticos",
    icon: "✈️",
    description: "Peregrinaciones, viajes espirituales y retiros iniciáticos a lugares sagrados del mundo",
    longDescription: "Guias y organizadores de viajes con propósito: peregrinaciones a Tierra Santa, viajes iniciáticos a las pirámides de Egipto y los templos de Grecia, rutas espirituales por Machu Picchu, Sedona, el Tíbet y la Amazonía, el Camino de Santiago, ceremonias en lugares de poder y retiros en monasterios. Viaja para transformarte.",
    keywords: ["viaje iniciático", "viaje iniciatico", "peregrinación", "peregrinacion", "tierra santa", "lugares sagrados", "machu picchu", "tíbet", "tibet", "sedona", "piramides", "pirámides", "egipto", "peregrino", "ruta espiritual"],
    color: "from-cyan-800/40 to-teal-900/20",
    borderColor: "border-cyan-700/30",
    textColor: "text-cyan-300",
    bgColor: "bg-cyan-800/20",
    gradient: "from-cyan-900/50 via-teal-900/30 to-transparent",
  },
  {
    id: "zona",
    name: "En tu Zona",
    icon: "📍",
    description: "Ferias, mercados, charlas y encuentros espirituales cerca de ti",
    longDescription: "Descubre todos los eventos, ferias, mercados esotéricos, círculos y encuentros que suceden en tu zona. Desde la Feria Holística de Madrid hasta el Mercado Esotérico de Barcelona, pasando por charlas online, círculos de mujeres y encuentros de mantras. También encontrarás aquí todos los profesionales de la app cerca de ti, organizados por ciudad, para que puedas conocer quién está en tu zona.",
    keywords: ["feria", "mercado", "círculo", "circulo", "encuentro", "charla", "evento local", "cerca de ti", "zona", "ciudad"],
    color: "from-green-500/20 to-emerald-500/5",
    borderColor: "border-green-500/30",
    textColor: "text-green-300",
    bgColor: "bg-green-500/10",
    gradient: "from-green-900/40 via-emerald-900/20 to-transparent",
  },
  {
    id: "materiales",
    name: "Materiales",
    icon: "💎",
    description: "Cristales, cuencos, inciensos, velas, libros y productos espirituales",
    longDescription: "Todo lo que necesitas para tu práctica espiritual: cristales y piedras energéticas, cuencos tibetanos y gongs, inciensos naturales y velas rituales, mandalas y arte sagrado, hierbas medicinales y aceites esenciales, libros de espiritualidad y ocultismo. Artesanos y tiendas especializadas que ofrecen productos hechos con conciencia.",
    keywords: ["cristal", "piedra", "cuenco", "incienso", "vela", "mandala", "libro espiritual", "herbolaria", "aceite esencial", "mineral", "artesanía", "artesania", "material espiritual"],
    color: "from-yellow-500/20 to-amber-500/5",
    borderColor: "border-yellow-500/30",
    textColor: "text-yellow-300",
    bgColor: "bg-yellow-500/10",
    gradient: "from-yellow-900/40 via-amber-900/20 to-transparent",
  },
]

export function getItemsByCategory(categoryId: string) {
  return {
    professionals: DEMO_PROFESSIONALS.filter((p) => p.category === categoryId),
    courses: DEMO_COURSES.filter((c) => c.category === categoryId),
    meditations: DEMO_MEDITATIONS.filter((m) => m.category === categoryId),
    events: DEMO_EVENTS.filter((e) => e.category === categoryId),
  }
}

export function getAllItems() {
  return {
    professionals: DEMO_PROFESSIONALS,
    courses: DEMO_COURSES,
    meditations: DEMO_MEDITATIONS,
    events: DEMO_EVENTS,
  }
}
