export const SPECIALTIES = [
  "Yoga",
  "Meditación",
  "Mindfulness",
  "Reiki",
  "Tai Chi",
  "Bio-danza",
  "Chi Kung",
  "Ecstatic Dance",
  "Barras de Access",
  "Nutrición Consciente",
  "Medicina Alternativa",
  "Terapias de Sonido",
  "Respiración Consciente",
  "Terapia con Animales",
  "Constelaciones Familiares",
  "Hipnosis Clínica",
  "Crecimiento Personal",
  "Limpieza Energética",
  "Chamanismo",
  "Tradiciones Sagradas",
  "Cábala",
  "Numerología",
  "Tarot",
  "Runas",
  "Mediums",
  "Astrología",
  "Ocultismo",
  "Viajes Iniciáticos",
  "Retiros Espirituales",
  "Ceremonias",
  "Ferias y Eventos",
  "Materiales Espirituales",
  "Pranayama",
  "Yoga Nidra",
  "Flores de Bach",
  "Biomagnetismo",
  "Sanación Energética",
  "Coaching Espiritual",
  "Registros Akáshicos",
  "Péndulo Hebreo",
  "Regresión a Vidas Pasadas",
  "Terapia de Línea de Tiempo",
]